apiVersion: v1
kind: ConfigMap
metadata:
  name: linkwarden-env
  namespace: linkwarden
data:
  NEXTAUTH_URL: 'https://linkwarden.raymondcollazo.com/api/v1/auth'
  NEXT_PUBLIC_AUTHENTIK_ENABLED: 'true'
  AUTHENTIK_CUSTOM_NAME: authentik
  AUTHENTIK_ISSUER: 'https://auth.raymondcollazo.com/application/o/linkwarden'
