apiVersion: v1
kind: ConfigMap
metadata:
  name: linkwarden-env
  namespace: linkwarden
data:
  DATABASE_URL: linkwarden-db-rw
  NEXT_PUBLIC_AUTHENTIK_ENABLED: true
  AUTHENTIK_CUSTOM_NAME: authentik # Optionally set a custom provider name. Will be displayed on the login page
  AUTHENTIK_ISSUER: https://auth.raymondcollazo.com/application/o/linkwarden
