---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-pg
  namespace: linkwarden
spec:
  instances: 3
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-db
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: linkwarden-pg-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: linkwarden-pg-store
  namespace: linkwarden
spec:
  configuration:
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    destinationPath: s3://linkwarden-db/
    s3Credentials:
      accessKeyId:
        name: rustfs-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-backup-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
