---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-pg
  namespace: linkwarden
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-pg
