apiVersion: v1
data:
    password: ENC[AES256_GCM,data:uEKluzJBSrhqocwUNlHPrLftHvpucYZ+0y1JnOZz3b5yM3ojcIpNeKu/0CuKVzt920eDd/PEawlWJBTTZGaogQc1sxTpVQ7g3FN4PW6k30k4EiyJo0yvxA==,iv:ddLs2aHCa/GYZSnbXMUJan7mN5YjjUaAAMl/E/q743o=,tag:1wqEz9f/nR3rr4FY922eVw==,type:str]
    username: ENC[AES256_GCM,data:7kdfB3cMzzcmnSw6VpNQlQ==,iv:42HRXGuueZA1A4sBUFF6mtgyLqh/doWQ6UPkY3TrxNQ=,tag:w5HLvcuTT412+OrsSlQSEA==,type:str]
kind: Secret
metadata:
    name: linkwarden-db
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNVpRSGFCV2d0Z3h5WEx0
            ZG4wOVZwTWprRk5OZ1V5YWZqNXpZVnZLK1ZjClQ5c0NhaDEvMVBrWkR5ZEFqRFhS
            SU5BTWZHckY5N05BbEU2S2lWYmRPV2MKLS0tIGF1NDlET2wrcTd0VU1nRTFYdXlq
            am12NUpGM1g5dHdMcnplTkZYaVJWelkKIKLa1NhrDCS6rbrkzwpPjmJ0Lv7ljLWN
            CZ6I7xeeqd3zU7pVbhsdL0IVQklXPAvgRpK6rPqK2ZC41+Zu7taGrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:29:00Z"
    mac: ENC[AES256_GCM,data:ZDN5KTU6jv3qMT3DGESsAwD7kpH3XnVz/eYdLiafU0yJIxdPAnSbQcimclxrHXWMbbiPlbo7SmqYGnOSW0o6wi9RoaZzwKZxTGwSMMrsOMgBXJUlkdMHvGM/a2NPGqv9+Fd6lmRiicnjZVbi44q7f/FYfD/SsNoPJt81X7111Wo=,iv:kbtVFAkYIGtsd5wh2CfF5L3JgPCgda31ARZztAG5YlU=,tag:OxXQ5fQWhb6kcazA1+2oDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:ik0F1oMN1mmTwbYBui0z+FwQzhQIquZlEQUAe/70g3z+ur6Ym57ean3bA56k7+Ot3lagQxgLviUZs0ZkWydfonVqoF2y788tkNCdxcUA7sUPWIv3lJThgg==,iv:fzWg9BEgXyWECYGciK1Tl59cEQ9Wu4XOhBPWKj5b1/o=,tag:iHFkzoi9NSdjwGsc/3dgTw==,type:str]
kind: Secret
metadata:
    name: linkwarden-meili
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNVpRSGFCV2d0Z3h5WEx0
            ZG4wOVZwTWprRk5OZ1V5YWZqNXpZVnZLK1ZjClQ5c0NhaDEvMVBrWkR5ZEFqRFhS
            SU5BTWZHckY5N05BbEU2S2lWYmRPV2MKLS0tIGF1NDlET2wrcTd0VU1nRTFYdXlq
            am12NUpGM1g5dHdMcnplTkZYaVJWelkKIKLa1NhrDCS6rbrkzwpPjmJ0Lv7ljLWN
            CZ6I7xeeqd3zU7pVbhsdL0IVQklXPAvgRpK6rPqK2ZC41+Zu7taGrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:29:00Z"
    mac: ENC[AES256_GCM,data:ZDN5KTU6jv3qMT3DGESsAwD7kpH3XnVz/eYdLiafU0yJIxdPAnSbQcimclxrHXWMbbiPlbo7SmqYGnOSW0o6wi9RoaZzwKZxTGwSMMrsOMgBXJUlkdMHvGM/a2NPGqv9+Fd6lmRiicnjZVbi44q7f/FYfD/SsNoPJt81X7111Wo=,iv:kbtVFAkYIGtsd5wh2CfF5L3JgPCgda31ARZztAG5YlU=,tag:OxXQ5fQWhb6kcazA1+2oDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:E5d9tfEosjMD9P3OA5VwUwM3Q4lPn3wfWrEMKbrtjUn0jpp3N/g9b8yKOVx6Pwh0BHdPdiOTvno=,iv:MTDqPoVK4qhZn8GBrOVIgbl0huXQN6gBE35CWdspIuk=,tag:h1ALMiyApQGB/cnCx+/1mA==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:DO0qKBz4sDwDY0TiXP+BHV3Vs4ts0eOzsG3/ft4oz2suEf0MEPqSDTnS03JhBmcZ0qwxLzBQaVckKckDYICJ3F75sp6WroZwOk9YZUDXfVkqDygjZhI/6xmvhcFlNkxPOieHvOIJ4hk6oonocbwZEfIHMzat5JsbHoFRobyCDrQZ+DuvTdMYYkodw6JZYXV05OFuJLyAWatc82lpl+vBcIpMUGgm49e4WB2cNA==,iv:/agklw7RymCr06cytoTqdVF9D+pNWeTHVh0iHuQRqpI=,tag:2BoNPNXZnz/EEpXqna492Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:NeuUasq6qLMpqePMqlbKfAi34oyjq7DlHBzwvi9xd8t8bxVgAtg8bb0GrXGGvaio7owRf4cuhZbSWDH6ODllF6eFtY047HzohA+sASBncuApE2v9apKFb/92bxfbQ2sIkKHfSmKYiZJgn6ksagKdwy7VW56BfUeJf7URbQrWjp6YFZ1go5S+HeVETpbJVumxWMVVgjehjNQsTXlNy5I/VnvRvR1T3WL2lnbLoOxIsO44hgjdX1oAajFyP2eldw6qyIlrnfYx344=,iv:oTT6qG9HGgD4xegrKYwSTWjS16cZtznXHYoxj3ZBh64=,tag:3m70iXgtVGAHDu8kSxC7fQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:FR3EGnx87vUEO6OLkfYtne9CX4ps62CikPN8ylrn3Q+7InBvYwXLuLfzzUvpQXA/CKAWDoExceJ1403W2xucxDuEj4DK4JJncR//Kd1KrNDS/VjLpOke/A==,iv:MoSrMW1UgqQtEV7o3Mc+AjEO6dqdNuHO/xbQ7/KqyPc=,tag:Ir4IM2Z4iLApQ2YTYQE+Ng==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:7wn5fAHLtvcsvTIrQJlxgFK0nNJruSCxd/fxcRNkQkSrlwQJM9/U4xLGxHvTlxsdJd+mqoaRdvLjRpQJyHiGdhzSNgrmXYp0e2tsZYh1t6TA6jlnbgdhqg==,iv:qzM2d7uxUkMePSwShUmf6XezeFHmbKGkjdd2/mZomJg=,tag:zYWGffxsk5LXcjQcF3f43A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:prYAGxxxkTqkrY1t97Yzl6GVuxyZ3bjl9qS7/cihSHj/DBI+zdW7TMpbOTOtQ4ngwPnTVpBOi03nddG9/zULE6445RxLVXdScnLMrkU06YaOsUdfKWJ14A==,iv:hK3Jlwm5H/pm+hC8c9GFOSorrwIJHHMi4jE7NWuT24U=,tag:XkQyXCzbDC5lcmY6mUuvzA==,type:str]
kind: Secret
metadata:
    name: linkwarden-env-secret
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNVpRSGFCV2d0Z3h5WEx0
            ZG4wOVZwTWprRk5OZ1V5YWZqNXpZVnZLK1ZjClQ5c0NhaDEvMVBrWkR5ZEFqRFhS
            SU5BTWZHckY5N05BbEU2S2lWYmRPV2MKLS0tIGF1NDlET2wrcTd0VU1nRTFYdXlq
            am12NUpGM1g5dHdMcnplTkZYaVJWelkKIKLa1NhrDCS6rbrkzwpPjmJ0Lv7ljLWN
            CZ6I7xeeqd3zU7pVbhsdL0IVQklXPAvgRpK6rPqK2ZC41+Zu7taGrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:29:00Z"
    mac: ENC[AES256_GCM,data:ZDN5KTU6jv3qMT3DGESsAwD7kpH3XnVz/eYdLiafU0yJIxdPAnSbQcimclxrHXWMbbiPlbo7SmqYGnOSW0o6wi9RoaZzwKZxTGwSMMrsOMgBXJUlkdMHvGM/a2NPGqv9+Fd6lmRiicnjZVbi44q7f/FYfD/SsNoPJt81X7111Wo=,iv:kbtVFAkYIGtsd5wh2CfF5L3JgPCgda31ARZztAG5YlU=,tag:OxXQ5fQWhb6kcazA1+2oDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
