apiVersion: v1
data:
    password: ENC[AES256_GCM,data:BbQBBjhyxX1dW8P9fZO9S+NyPImuLc6pf4pV3afaAfIvN6/TXd+HWIw1ez/tUu87kME2i1rII+rh/47HIrY+sZfPZXtIoWkigJFhgDV2ru3wYfYtlvp2nA==,iv:2Zfe9YsN1SWXgRpBrpaYvoxkLVRcqnuP9JLrX2wylGs=,tag:UIEiY8Y9b9QwM93DgVGo3A==,type:str]
    username: ENC[AES256_GCM,data:2aiYZXT/7ukxtqVfG5/HIA==,iv:oeucZlxFVAYbbmGL4zj10r5pqIu0jZUnkJlQJj+zZoI=,tag:3t1pRK4IOriMgn+94EgjBg==,type:str]
kind: Secret
metadata:
    name: linkwarden-db
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXBaZ1VHZkpJa2JQajRG
            Z1hBekJuREFYa0hIMm1UR0xHSmNtdjF0bFE4CnYvbDVUTjQxQUJ0Mi9MUm54RXZ1
            MGI2akpXek5rMWZaMkhKMnRjNDJQT0UKLS0tIGJJUmxYY0EybHlRSnp5MmFtQ1dZ
            djRyV2FEOUpyL2lzbG0xQ0JrMHFxTzgK/y2kqVUxqgBwkHYirE5e5WKxe7F9n+zU
            BNmHTS4vg9Vj3CC7wqPwyp3hja6otPcyVg6SZRCyiIsSJ4uSqEfhDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:04:50Z"
    mac: ENC[AES256_GCM,data:AoZ+ruTIV8T1uZv2iWcEbCv0EwP1yR3bT1xrhVepR+DEoJgYMM5Py7Ty9GSPzl+8ASvnx6MfC5CRjZOZn/z+5L+QqBv/ATHPbvoVsRKHW+QSr0QRdtXrC/yrZUSagbOcZCoxICJNSGTj03wH4TH+DBqx1y8F7zPSS78n3n5WtAY=,iv:hxYJyodPP01wrpDmHtXaeYBVqVA1C5iQksOabqKiPhY=,tag:iju2oFLrUkLYXujxcSrWIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:8hi1UeMQD0SgwzvPw1Sljyjlke2Mb9r51cdSWuldj1GE49qmsOoZppHrNDpce3QO3o4KuqJRI5XG1YrOJiwlzDomdMigfXoZ1QLFHe5yRGC8NkLwBnllNg==,iv:Qp2PXVOBUaymqbL3PbyEfjGdwWlABOhmZ6bwRzEExLQ=,tag:WIo4f2hmY2KDxMc8a0q7cQ==,type:str]
kind: Secret
metadata:
    name: linkwarden-meili
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXBaZ1VHZkpJa2JQajRG
            Z1hBekJuREFYa0hIMm1UR0xHSmNtdjF0bFE4CnYvbDVUTjQxQUJ0Mi9MUm54RXZ1
            MGI2akpXek5rMWZaMkhKMnRjNDJQT0UKLS0tIGJJUmxYY0EybHlRSnp5MmFtQ1dZ
            djRyV2FEOUpyL2lzbG0xQ0JrMHFxTzgK/y2kqVUxqgBwkHYirE5e5WKxe7F9n+zU
            BNmHTS4vg9Vj3CC7wqPwyp3hja6otPcyVg6SZRCyiIsSJ4uSqEfhDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:04:50Z"
    mac: ENC[AES256_GCM,data:AoZ+ruTIV8T1uZv2iWcEbCv0EwP1yR3bT1xrhVepR+DEoJgYMM5Py7Ty9GSPzl+8ASvnx6MfC5CRjZOZn/z+5L+QqBv/ATHPbvoVsRKHW+QSr0QRdtXrC/yrZUSagbOcZCoxICJNSGTj03wH4TH+DBqx1y8F7zPSS78n3n5WtAY=,iv:hxYJyodPP01wrpDmHtXaeYBVqVA1C5iQksOabqKiPhY=,tag:iju2oFLrUkLYXujxcSrWIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:WtmhRbmKkDxHARfx+CfkQLs+oo67UTyrZseQwDkHxBoOivl1QwfrUupfQhJrPBR/cp99S5B5AtU=,iv:CuumWr/zgn+wpLbiZpnmyDXIWzi5QHbIN2yxEDvOLCk=,tag:AK/Od9FdCStLzX8dJKIzYg==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:1ELPkfbU4ZS7gw5eYWRZ3usAX9cjgkxLhPmZpHJDUlY=,iv:4B1rNpugnTMwKKtyKk1STW5ICp7hLOQAqzBMs29y7Io=,tag:EKrrATj7plXePZSxvl5Q2A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0aBjFuiYzZnFGf1ZQnyQ6hHPa9JKiM/XakdhE4snYRU67GslNnUPrFmCHcJNBuBS7RcfApkJcuGgz0NBQumISTn3bNedRhIvkbOP+rcRWUY8ad67wwZZ+XoXJExqg7J3tadj9lZ82jESMX/HN8Ay2dbF3icFd5o/aaW1TU0twCdblp6TOSPbFfv9/pkn6WEVaha8dJ5fexhDWbSe+RaK7qZ6lSHFoRGNL8hKETUptZb/dkbt7zqVr3lB06l3+WjfM6mP5fISvvk=,iv:5ZI2MOgi1fZtlbSQt/ERCiyufUVZbDOflMzOrDjAqvw=,tag:O+CDYLYMstjVAAITpobGAQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:DKcdV3YXm9w+7FcNVeJjkBza439JcDrmx0QERVgLxaKtJJ4x58g65xroFw7qfcI/OhWPFjp6fTsMTY0ePeQdVyO0qNW2Ap3osGX+Yz1oqQGS9AVzdWsXtw==,iv:2GtknoJ45XOnSmpbCBYDqL8BDMW3BYljjglrY0UfW1I=,tag:pDnsK6jiXVu0sFXooHGyyQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:LaqNpDB6tFVRhReIEJgQPm1huyUC/vT6EE+1Bat8hsHnzxTuH6aD9ASAu0iJv6HYCgHzC2YxUATF8XmIjc2RldhZSmVUAAqbBdajaIz2fbBOzNjZlfm/EA==,iv:jMTIV2ZGjrappcNwwjWEhEKjObbIY0nmJo3I6bVLnmc=,tag:7NS5N+ZwtBRbvhG2lH3CrA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MBzCjn0WgbmtC8vWy2/5Ppxu7sNM7wOJWKNh5OhdJxEI2iOBAj0PXgpGeQtibwQFJmWtw+RcTIvaOZPL8jKy/muCRlOAlhG+2UaLMO8iXe2G1FlfauexNg==,iv:xNt8OSE9QeetMyZL4tdmIeCpmMXlHLdK82c6S++rnVE=,tag:+6EmsaRxn2+XZfUbRMlEDg==,type:str]
kind: Secret
metadata:
    name: linkwarden-env-secret
    namespace: linkwarden
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXBaZ1VHZkpJa2JQajRG
            Z1hBekJuREFYa0hIMm1UR0xHSmNtdjF0bFE4CnYvbDVUTjQxQUJ0Mi9MUm54RXZ1
            MGI2akpXek5rMWZaMkhKMnRjNDJQT0UKLS0tIGJJUmxYY0EybHlRSnp5MmFtQ1dZ
            djRyV2FEOUpyL2lzbG0xQ0JrMHFxTzgK/y2kqVUxqgBwkHYirE5e5WKxe7F9n+zU
            BNmHTS4vg9Vj3CC7wqPwyp3hja6otPcyVg6SZRCyiIsSJ4uSqEfhDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:04:50Z"
    mac: ENC[AES256_GCM,data:AoZ+ruTIV8T1uZv2iWcEbCv0EwP1yR3bT1xrhVepR+DEoJgYMM5Py7Ty9GSPzl+8ASvnx6MfC5CRjZOZn/z+5L+QqBv/ATHPbvoVsRKHW+QSr0QRdtXrC/yrZUSagbOcZCoxICJNSGTj03wH4TH+DBqx1y8F7zPSS78n3n5WtAY=,iv:hxYJyodPP01wrpDmHtXaeYBVqVA1C5iQksOabqKiPhY=,tag:iju2oFLrUkLYXujxcSrWIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
