---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-capstone-pvc
  namespace: wordpress-capstone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
