- Repositories:
    - kube-homelab:
        - href: https://github.com/RamonCollazo/kube-homelab
          icon: github.png
    - learning-lab:
        - href: https://github.com/RamonCollazo/learning-lab
          icon: github.png
    - devops-best-practices:
        - href: https://github.com/RamonCollazo/devops-best-practices
          icon: github.png

- Cloud Platforms:
    - GreenCloud VPS:
        - href: https://greencloudvps.com/billing/login
          icon: https://cdn.brandfetch.io/id0SQOHn0d/w/2048/h/2048/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1768745422984
    - RackNerd:
        - href: https://my.racknerd.com/index.php?rp=/login
          icon: racknerd-dark.png

- Cloud Services:
    - Cloudflare:
        - href: https://dash.cloudflare.com/
          icon: cloudflare.png
    - Netbird:
        - href: https://app.netbird.io/
          icon: netbird.png
