---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-community-operator
  namespace: mongodb
spec:
  interval: 15m
  chart:
    spec:
      chart: community-operator
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongodb
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
