---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tesrUEv1YQlygc08WLNZbcH92w7eURq0uaM+kaSzm6usT3Z184feZ6yUopYm3urY+rKKlnkglXTfeKZJ1/3jeuG8YfD6dWdEXs3kl3kAVEC4w61kzL/asg==,iv:BcARqUOV6g0RJegx0dBbtRq2iT5WxInKqb1W4vqAqDw=,tag:18UkzXojuTExtldW08YYaA==,type:str]
    username: ENC[AES256_GCM,data:sl3VGctwwFE=,iv:3FNjPfdr3gkEcp4XirLt5neufAWECfp2VCEeeou056A=,tag:9009rHHrviwzHvmLkJw1hw==,type:str]
kind: Secret
metadata:
    name: netbox-db
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TFJoc0hNbFl2WlJnTjFR
            MHFCZHg4U1oraDI3VjV3WW5IQ1RTT1RYOGxFCk1uZkJXeDQ3RENIeUZibTVFR0dx
            NWFrUFpCejArRk9rUVJCZlRBRFpoTVkKLS0tIFNvQ3ZHWHlQd1JYMmtzdXdYK3dS
            WUp0WGRlUlpwajdlTGZhM3EzUWlseEUKy+J0bBhR8DMQ2/IOIhdXzWqJlaTPXmmI
            hu1Whlpw93DxilSeClJvyu9tH3pTwxvNSgGPSBcaPOIUN9dXPNgINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:22:28Z"
    mac: ENC[AES256_GCM,data:kV1Igt0AVY2R4ukuK7CJIpnhn/ohoh4jECZs52+YOwIxaS2ojcy5mhnln7x01q1HJSsUpZVMp6w4/py7293P64f46OHHvj55qgb5U3YwSmBYbN8D4gCQUeLdyd8mVLc3u1Eg69C+WnRpCYGcn5IasJjL93M4/31HpC0SrYU9UEQ=,iv:d9mlPzjzvyof7iVwbxi3oRIsJfqp9c+nbxJ6J+Qyck0=,tag:hmvtPy+Dmzyc/P4BV4unzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    api_token: ENC[AES256_GCM,data:Y7t2vWRRapXMey+UreXYv5f6JTV8H3bl9RimLICXRIlkhK53b8t0H58rgEst1RHeX9ySZKMP275p2RJh,iv:i2OxO1RrCrVAf50W74GKhiavNd4nDwCxoXbqPthItIU=,tag:OAMx7hirSO9ZjJ2rD/tnEQ==,type:str]
    email: ENC[AES256_GCM,data:INdzVr0r2TjnyFPl4DLiJZ8hrzdbw3m8zhcQp/AogbE=,iv:nGqzSP1RHcOs0avnfV5lADmz/5mWnrWByLzNrqQZsGw=,tag:MDRZqt295MtxbV0R7VQjbg==,type:str]
    email_password: ENC[AES256_GCM,data:iv6/EDGfBe7peactNDzOcit079GEeih8VskH8vFbtfI7yBxBP5VJ/+GeSNYXv/Rlz7dFNvOxjvccM4Au,iv:8fV4buC6URqcCAb/vfmlYjcVARejbHzyrV8PdtqK/dg=,tag:FyoMnl8azbMOnOIB5lxCVw==,type:str]
    password: ENC[AES256_GCM,data://JKNwXUVfiMAmb/41mR7UR/nNHGbHZTTYlIKoUUjyzJgSBESGxY8O3qKmcLwp6hSyGYN1NEurWCnjHR,iv:/EWb32GjOJ5eKDFSPLoAazb7QOGpS1RxaQCPwt6gdQM=,tag:a+dYLPq4B6hdRTxksbfVrQ==,type:str]
    secret_key: ENC[AES256_GCM,data:ye6DmOdhyhbU8LBngcK9YJCVtxVVWIG5QkIGj5DvkxvolYzoJwORmJddogGY55N9E71Ld7Ii2b6b2vuERVOd9+dpYvVRmVmRisNTsUl5ZLcOTOjJwc9szSN8l90=,iv:Z4HICgVpenKaKJtoN0A9AdN9kMvrAdJpJ/eyJwDMMXE=,tag:gtmYn721wpun3vcsDviarw==,type:str]
    username: ENC[AES256_GCM,data:qx/nNN483kk=,iv:1utkqTEgPutcTqGxPrzX4S6T2Oyx5nB+nxfPji/buOo=,tag:xfkPL7ksgrRrw+cUNyyk3Q==,type:str]
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaHhOVDY2elY3TXVwZS9M
            dWdFSXlZNDZmNS9hWk5DN1p1T3JpZE9qcGdBCitIVUlzNDhmTnp0VmlEYmFKQjNu
            REhDNlZ6RUp3MzFGOFNQUGRST21iSTQKLS0tIEQ1bFVyZFpJRG4ydjFYSEVhQmNu
            VUN5ODZOVmVsY0J5bWdkOS9Nck5SS28KOB0LpdlYusUZyC1E4ypkrQHZp+qQ5/QC
            eJrJ6dI+aUgvxguz7FnQ101yAsICNIfHXmzlm/alnHO8HSAfFKczbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:47:00Z"
    mac: ENC[AES256_GCM,data:xMnmLtdcAJ5WxCEtgVf38tzVBx1rbB7Sh039lr/LJGM9SNFWyFaisuRM2gvycjJB00qQtCSUbUBE8QDBoMhI8oboM4gprAxd9mL0e+j06hafqdu+m7wjpzewgvqRaDbldvxYdRnRz2Vb4tN890mQxnW+RrrWmxKs8vmiqbMnO84=,iv:8d2/fHXCGPI9Ymp+ABsZj0DgLyrRHc11ZKVJASUc34g=,tag:Bmcm0izPLTBXxaPsUD8wvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    oidc.yaml: ENC[AES256_GCM,data:IkyZoYOTRvda3r7Dfwl7BJNthPquXw3hcT3ajyR5IFWimZDKyEY0MCzA/ckEUgaPayBQ6Ws+IY5bKkyQkKU+ShRm4t5YX5fpGC+DKYO4RFlt2RJD8UvcQq4aLdmmNB71J82Si1/2B15Kdhrl4+91/4XOMT735XZ0d6+2CdIXDmPjcTkOLFln0VjkQThuR5tKy+bjAvWEhyhJbmNQELLsewhoFlQzfCHjuBqHHouDbfBFeP9Kqlama0reVO8voJQfrPYGBrzzHYUsQBk7QLia7Q5+zS/UJGPZkiPuXbSbi878LOl/huYcTojE0LSrE4xg2LCIwguzcEI//DWT6czt2aYO6mccBLfFMtBtR3lsWSnn2WPFFHVR35HjUYBUsHi+MCOJWNtTkaY94y5ety0AYVySyU6l76FuzQkpO2n4Bq4RUbDGkEx86sAvK/X466Q30krCtRB5IMmdBfUAf8NAogegUfOT+4qCybeTOpwrZClGXN2oS070p71ybQEBy+h8cV1pBolUa2WbIJgfT5sjXF3pKdR1impKw+9llcywJ9yRxryJD8u05gJ/Ct+wqYjGru3uM7CdMYp0yg6yii7mVwJWA2jPSO0v0UhCpNizoYs4RzzJqTDreIX3qDF8sDTaFEmqPpxLFneVO3wz+Ofx2YEnShzPL1Z7vZ9cSatg1eepdKWVwT04uJsLLDWkui0noQugW0kKxZs7RBairaSz3vWj/ttTeUTtTud6VbCBcCc=,iv:uwJyHonFfIEWt7n2oIpWrZtXCUnUZ5VO8BJssLGdsaw=,tag:OtzKir/MJHac6wbrB5tO/Q==,type:str]
kind: Secret
metadata:
    name: netbox-oidc
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM0JTcHh3b24yU3Izalov
            dTN1K3o1OVp3TnY4MVVKaEtONk1SamtzQjNFCi9UK0taRVNMbFhVMXRIMlJqd0xu
            TnA5ekVZTWVOaHJWK2cvN056RXBCQ1kKLS0tIHhLN25DYnNNM2k5QnFCSFBQVVBo
            L05FaUdZUjlZeStRT2gza2sxdnQrQ0EK7q5ne0taLmSHewK2aYvwA2W4Nk6eMJQ2
            fMdtUs1h3s7YN2sXxZuViI+QxZ6DC77tgoxNZOj1uLPRodb6vJO0Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T04:19:25Z"
    mac: ENC[AES256_GCM,data:6q9Da+qOF4iwnrYMEwbLyu/WHsTI5xfyMkwYwvYngjcbji8A6EQFFG1CQSt+9o92S+sotWvwzV9vF93R4VBQuDfK+iE4AjF/GtuKnNF5LzNseFirQu4tyMtrvCQiJ53pBkxO5eWvY6iuZTiICMR6uWlVXKJRVhUErkFVPV3OLIU=,iv:cbstrm8d7Deo2EkTMS9yUPjcWVsFbL9LbyXzbuu5nCE=,tag:NE9PcFy61JqnsIMKRLSBlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
