---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tesrUEv1YQlygc08WLNZbcH92w7eURq0uaM+kaSzm6usT3Z184feZ6yUopYm3urY+rKKlnkglXTfeKZJ1/3jeuG8YfD6dWdEXs3kl3kAVEC4w61kzL/asg==,iv:BcARqUOV6g0RJegx0dBbtRq2iT5WxInKqb1W4vqAqDw=,tag:18UkzXojuTExtldW08YYaA==,type:str]
    username: ENC[AES256_GCM,data:sl3VGctwwFE=,iv:3FNjPfdr3gkEcp4XirLt5neufAWECfp2VCEeeou056A=,tag:9009rHHrviwzHvmLkJw1hw==,type:str]
kind: Secret
metadata:
    name: netbox-db
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TFJoc0hNbFl2WlJnTjFR
            MHFCZHg4U1oraDI3VjV3WW5IQ1RTT1RYOGxFCk1uZkJXeDQ3RENIeUZibTVFR0dx
            NWFrUFpCejArRk9rUVJCZlRBRFpoTVkKLS0tIFNvQ3ZHWHlQd1JYMmtzdXdYK3dS
            WUp0WGRlUlpwajdlTGZhM3EzUWlseEUKy+J0bBhR8DMQ2/IOIhdXzWqJlaTPXmmI
            hu1Whlpw93DxilSeClJvyu9tH3pTwxvNSgGPSBcaPOIUN9dXPNgINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:22:28Z"
    mac: ENC[AES256_GCM,data:kV1Igt0AVY2R4ukuK7CJIpnhn/ohoh4jECZs52+YOwIxaS2ojcy5mhnln7x01q1HJSsUpZVMp6w4/py7293P64f46OHHvj55qgb5U3YwSmBYbN8D4gCQUeLdyd8mVLc3u1Eg69C+WnRpCYGcn5IasJjL93M4/31HpC0SrYU9UEQ=,iv:d9mlPzjzvyof7iVwbxi3oRIsJfqp9c+nbxJ6J+Qyck0=,tag:hmvtPy+Dmzyc/P4BV4unzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    api_token: ENC[AES256_GCM,data:Y7t2vWRRapXMey+UreXYv5f6JTV8H3bl9RimLICXRIlkhK53b8t0H58rgEst1RHeX9ySZKMP275p2RJh,iv:i2OxO1RrCrVAf50W74GKhiavNd4nDwCxoXbqPthItIU=,tag:OAMx7hirSO9ZjJ2rD/tnEQ==,type:str]
    email: ENC[AES256_GCM,data:INdzVr0r2TjnyFPl4DLiJZ8hrzdbw3m8zhcQp/AogbE=,iv:nGqzSP1RHcOs0avnfV5lADmz/5mWnrWByLzNrqQZsGw=,tag:MDRZqt295MtxbV0R7VQjbg==,type:str]
    email_password: ENC[AES256_GCM,data:iv6/EDGfBe7peactNDzOcit079GEeih8VskH8vFbtfI7yBxBP5VJ/+GeSNYXv/Rlz7dFNvOxjvccM4Au,iv:8fV4buC6URqcCAb/vfmlYjcVARejbHzyrV8PdtqK/dg=,tag:FyoMnl8azbMOnOIB5lxCVw==,type:str]
    password: ENC[AES256_GCM,data://JKNwXUVfiMAmb/41mR7UR/nNHGbHZTTYlIKoUUjyzJgSBESGxY8O3qKmcLwp6hSyGYN1NEurWCnjHR,iv:/EWb32GjOJ5eKDFSPLoAazb7QOGpS1RxaQCPwt6gdQM=,tag:a+dYLPq4B6hdRTxksbfVrQ==,type:str]
    secret_key: ENC[AES256_GCM,data:ye6DmOdhyhbU8LBngcK9YJCVtxVVWIG5QkIGj5DvkxvolYzoJwORmJddogGY55N9E71Ld7Ii2b6b2vuERVOd9+dpYvVRmVmRisNTsUl5ZLcOTOjJwc9szSN8l90=,iv:Z4HICgVpenKaKJtoN0A9AdN9kMvrAdJpJ/eyJwDMMXE=,tag:gtmYn721wpun3vcsDviarw==,type:str]
    username: ENC[AES256_GCM,data:qx/nNN483kk=,iv:1utkqTEgPutcTqGxPrzX4S6T2Oyx5nB+nxfPji/buOo=,tag:xfkPL7ksgrRrw+cUNyyk3Q==,type:str]
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaHhOVDY2elY3TXVwZS9M
            dWdFSXlZNDZmNS9hWk5DN1p1T3JpZE9qcGdBCitIVUlzNDhmTnp0VmlEYmFKQjNu
            REhDNlZ6RUp3MzFGOFNQUGRST21iSTQKLS0tIEQ1bFVyZFpJRG4ydjFYSEVhQmNu
            VUN5ODZOVmVsY0J5bWdkOS9Nck5SS28KOB0LpdlYusUZyC1E4ypkrQHZp+qQ5/QC
            eJrJ6dI+aUgvxguz7FnQ101yAsICNIfHXmzlm/alnHO8HSAfFKczbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:47:00Z"
    mac: ENC[AES256_GCM,data:xMnmLtdcAJ5WxCEtgVf38tzVBx1rbB7Sh039lr/LJGM9SNFWyFaisuRM2gvycjJB00qQtCSUbUBE8QDBoMhI8oboM4gprAxd9mL0e+j06hafqdu+m7wjpzewgvqRaDbldvxYdRnRz2Vb4tN890mQxnW+RrrWmxKs8vmiqbMnO84=,iv:8d2/fHXCGPI9Ymp+ABsZj0DgLyrRHc11ZKVJASUc34g=,tag:Bmcm0izPLTBXxaPsUD8wvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    oidc.yaml: ENC[AES256_GCM,data:SsyYPOiG9mRljj8qDtqBeB1s2QYwQR9tVjzadK6TwXR611lWjYTqc+zNeeaqaU8ciOjX3yhiSbncIKYwrtMexSvag2aHLvdldUzlvhBAUgFd3MCj6Z6I0m7W8ixWEdRqDf9xfADflOdDl2LWuJWX0h7FdFFBnEaGL/tTTc731eEabY5x5hOC3Q0Gx+PrGZpbgHRC8jkWN3oNKB+P+APybhwfQI3Zs7Wq6+bjt44L/y30iLNXdhyWC5SRU9Fl095L1L55nigQPmdfMdqCjklXU1ABaABxL8JGjfEXMSSWAjOHqtEXi2Akc/Tq1Em/U9vtMirStliJ1uzDQgsivROv2+cludA4o8Vkelos9SQ927NDeYhA/xf4g6mKz90Uk3UbgJVLulT/T523WK3yJxqJZZcEIDw6ANzTPWPn1cTIbITaq/JjREwB8vZlsxNncFjOgSfQAWGXviFBfDGgqQzBBWZsI2q+J5jRhCLSkza0oWrZCVoaKxzIhBqv0y2Nmdg6bUVVG4aQfZV3S/snyOmUnFv2mHJu9KtsHTSTTzrYjcsxiZaSVgPOOSYddCRS/VsaysVs4IQTJvaNGDwnpO5GY7+LD4kUrtrRsxFOBVDoSbQ=,iv:CyHgSh7f/mNXxXiyI6c+wuaUK9rYEllofPNv/vRzN8Y=,tag:B4IEJOpz+XM+7BeIt5UFnQ==,type:str]
kind: Secret
metadata:
    name: netbox-oidc
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOXZOSFZMa1ZPRDYwNHo3
            M0dxUzY4bSt3OFgyeU9XZm03aDdxZGVueEhnCmxXdTB6M3daMXZKTXNDYUFrdmls
            Z2dWRXBLSWphdGtISjZ1aXY2ZGJiNHcKLS0tIER3NmF3eFdJaFp3Q0NVUi8xUDhZ
            S0VUSGlvcEFsT1dQenMwNDBrNWN3eVEKoOf5A2qTsjk/eazIfAWz6A/CK/Hs7d5r
            zFnmekNaDiiciGvlimvIwox4OqGhA5j7u+9Sv7APB4gM1PD0JKNPMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T04:10:10Z"
    mac: ENC[AES256_GCM,data:S8399SgmuOto2IgRNMvu/oYeRRMrD5tbzQRnEDNymDqhhtxfggyRG5vaxe1KZSmJPTQLqt61BEfrwC3Bx7WTs1EoTWKYBAjdiJQEqyTPHDX7rPDVICzyC+bq5HCFDgOkI1h+BXx2bbrzQgbz3tEXG42U9VA69sNJOHpggjZafiM=,iv:DYNu2DpZ0U3kphj5TQnbeuJcMhU8p+C/GbR2H9FqiKo=,tag:a6ITEugzpPWsxvtAHfHcLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
