---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:tesrUEv1YQlygc08WLNZbcH92w7eURq0uaM+kaSzm6usT3Z184feZ6yUopYm3urY+rKKlnkglXTfeKZJ1/3jeuG8YfD6dWdEXs3kl3kAVEC4w61kzL/asg==,iv:BcARqUOV6g0RJegx0dBbtRq2iT5WxInKqb1W4vqAqDw=,tag:18UkzXojuTExtldW08YYaA==,type:str]
    username: ENC[AES256_GCM,data:sl3VGctwwFE=,iv:3FNjPfdr3gkEcp4XirLt5neufAWECfp2VCEeeou056A=,tag:9009rHHrviwzHvmLkJw1hw==,type:str]
kind: Secret
metadata:
    name: netbox-db
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TFJoc0hNbFl2WlJnTjFR
            MHFCZHg4U1oraDI3VjV3WW5IQ1RTT1RYOGxFCk1uZkJXeDQ3RENIeUZibTVFR0dx
            NWFrUFpCejArRk9rUVJCZlRBRFpoTVkKLS0tIFNvQ3ZHWHlQd1JYMmtzdXdYK3dS
            WUp0WGRlUlpwajdlTGZhM3EzUWlseEUKy+J0bBhR8DMQ2/IOIhdXzWqJlaTPXmmI
            hu1Whlpw93DxilSeClJvyu9tH3pTwxvNSgGPSBcaPOIUN9dXPNgINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:22:28Z"
    mac: ENC[AES256_GCM,data:kV1Igt0AVY2R4ukuK7CJIpnhn/ohoh4jECZs52+YOwIxaS2ojcy5mhnln7x01q1HJSsUpZVMp6w4/py7293P64f46OHHvj55qgb5U3YwSmBYbN8D4gCQUeLdyd8mVLc3u1Eg69C+WnRpCYGcn5IasJjL93M4/31HpC0SrYU9UEQ=,iv:d9mlPzjzvyof7iVwbxi3oRIsJfqp9c+nbxJ6J+Qyck0=,tag:hmvtPy+Dmzyc/P4BV4unzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    email: ENC[AES256_GCM,data:cVwFiMbzpnjHKtu/iX4NUCrCGSgtdk7aMJ/rYZv8lU8=,iv:Hx8fsrDxKuWqv+N9upWbald9kH/DzjT5TBSruKFljug=,tag:+P0twnaKLS6Uha+/1vjHAA==,type:str]
    password: ENC[AES256_GCM,data:0swdqogSRpY+aKCPmD98Lvf8Zhv8DKMyMCgSNctIk4wPyOG4/0vjqsvU0XNmIXCZnRBWwzncTRI3eTye,iv:6XePGecsNSmrBPQUePCVo+0fUsgyHn7UPSq3Ghslntw=,tag:O/P6Mwr3CbbFA0DEhLbjkw==,type:str]
    secret_key: ENC[AES256_GCM,data:sXK6l3deNwZvJO3N2dpisfdfqgv5a0sQ/k5d4oi6s0J72lGOqUXy35ntbQuQXAJ1Zxo/uaoqQeoAHzSsA4wSraE7mZReoEvizZEnBTjEcgsNeX/APJEBoBJz6os=,iv:uAlulul88itNVP9MpamWvYbzPgK6DjYXt8NQsofBFKM=,tag:RKHCfc2yMRwrUp4+wHKZvw==,type:str]
    username: ENC[AES256_GCM,data:K9Up2ifXAzg=,iv:iDRVDMtyPCghS1mL8lLau0SxVDGocWUOaAmGgvuyKOk=,tag:qFwMbAF1Qxuap/aed3e+zw==,type:str]
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeHN6RGVyTXg5VGQvQ3pi
            U2h5SVFLclI4cXYwdXFRaW83L1g4YWRtbXpRClFFdkR2ck9wVGg0dnU5cEVmeDM0
            Yy9XS08vYzhmNmsyUXRsMnZTS0E0NEEKLS0tIEpJTDh2ejBWQU1JU3g1OVdtaXR0
            SzBiN0l3OGl1UUw1TElKTkU1Y3c2SGcK+usCX7uWT5vL5s+WT6Wx9hq6vxOklsEo
            hoDtZWAoou71COxXQcjSv6dD2I7iDiEK/xWVJcgVMDlaYI5ddJDc2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:38:28Z"
    mac: ENC[AES256_GCM,data:OZujFU8/32zbq2ByyzkguNfsyynYyXUEaxQZIXoIXhSsgPrtUsrQiyxbttbW7RjAv6X5kWZeIpYzJiHp/Q0O5OnyFCMP51UbiFFllRCCmaMX2Cg1muzpDytV7+iUEnaN7Y+VKauvswo2FZQkrnub7MBbW3XLv0Pm2XrAZ/v6c7k=,iv:5ZJO2Av+dme19I2HRuTFluPfKYdbe293c3KRBgdY0SY=,tag:WvwWrIRMQWidhjtV3auDwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    oidc.yaml: ENC[AES256_GCM,data:hHUAhxO6YITAckf+b2n7Cr+2TObggQ4467fW5iHLZUx7KWr3UPtAoEY1Za+LSseIAtRcrCXQUnfQo0+43mvjU/iAmepNRHtg4AXkRdcDrgXgrZgT1I/uahOp4l5/E5RPVKmDKMZiEjvSKOMfF1we4k61s/l+E7Shl6VWGvxSaw/7IvD8OgeeXPfuHXOLASFzMvLDwB7Vn0bmpsZhM3FjjwjaQULLGEDdwBKKTrYt71/MO77WC0aOa+1p/y0CbAcVvsDD4zkpzc4hO4KUXWJK2T5/SuXvXomWuZjfwH3uz2u85Baog2ee7rndXyVkynxpUi2vGlKVFWFu6wLjKrwl3BVkkIRqFtya/42vIplWz93Homa/Ble5+Wreg3PCw/ZmPL3NaR0o0VG85chtfUzdTkAFfetB+76+xwu6AuoUl9qSdj/wxPUiql5+ZVHk8ZqUstpOIFdH+v2QN2JHmmQtczCeYB9oRA+TXlesMwyGjNz0/3S0GvYSXRUcRN3ICzD3dkSVrkbjqPgk712fqsXPng1dVdZI2A8CsiB7ow==,iv:5m45p+EqHZkSzEXk7Zm4OTqtNxXvxb3GXVbVkpuOm8A=,tag:3ZGCC+BnaPfxmxRs8DNQtA==,type:str]
kind: Secret
metadata:
    name: netbox-oidc
    namespace: netbox
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TFJoc0hNbFl2WlJnTjFR
            MHFCZHg4U1oraDI3VjV3WW5IQ1RTT1RYOGxFCk1uZkJXeDQ3RENIeUZibTVFR0dx
            NWFrUFpCejArRk9rUVJCZlRBRFpoTVkKLS0tIFNvQ3ZHWHlQd1JYMmtzdXdYK3dS
            WUp0WGRlUlpwajdlTGZhM3EzUWlseEUKy+J0bBhR8DMQ2/IOIhdXzWqJlaTPXmmI
            hu1Whlpw93DxilSeClJvyu9tH3pTwxvNSgGPSBcaPOIUN9dXPNgINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T03:22:28Z"
    mac: ENC[AES256_GCM,data:kV1Igt0AVY2R4ukuK7CJIpnhn/ohoh4jECZs52+YOwIxaS2ojcy5mhnln7x01q1HJSsUpZVMp6w4/py7293P64f46OHHvj55qgb5U3YwSmBYbN8D4gCQUeLdyd8mVLc3u1Eg69C+WnRpCYGcn5IasJjL93M4/31HpC0SrYU9UEQ=,iv:d9mlPzjzvyof7iVwbxi3oRIsJfqp9c+nbxJ6J+Qyck0=,tag:hmvtPy+Dmzyc/P4BV4unzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
