apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  interval: 15m
  chart:
    spec:
      chart: dragonfly
      version: 1.34.2
      sourceRef:
        kind: HelmRelease
        name: dragonfly
        namespace: dragonfly-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: dragonfly-values
      valuesKey: values.yaml
