apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: dragonfly-system
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/dragonflydb/dragonfly/helm
