apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonflydb
  namespace: dragonfly-system
spec:
  interval: 24h
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
