---
apiVersion: v1
data:
    HOMEPAGE_VAR_GRAFANA_TOKEN: ENC[AES256_GCM,data:mVtOBaXd2qNaF9W8XW1dbv+sUTQ1OfMiGXec//+EyBocF/jAH+Q6s1ifB90hBzVieHE7+tVZftfU6e8ymYgSIw==,iv:2rX3UgM61Y9ehL4mA8T6XZoNqORKtGxpCD3j0A17NmM=,tag:tnKtUFNY7hvSUAM4IzIW8w==,type:str]
kind: Secret
metadata:
    name: grafana-token
    namespace: homepage
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTU1vRDFRREFadE9TOWUz
            cVhIZ0lZMEVXWERkS2dFUHk0Tnk0cjEvT3hjCmcrTHhWRW93azhvWU1QdEFjcmds
            RFdkOHkvRnFGcjBrYkZzckEvbEg4TmcKLS0tIDAyOTV5ekcyTUF1TUd1MGo4M1hD
            RndtMXpZYTdDeUNmT211RWt6TGxsRHcKhhNmN8zhfFdlZeDs6a+EelOsYK6Bcoa2
            0DdqnwlOZNHT7pJJ0PedT4mZ1c/Kss2YvZS6KPZcatb7m+bpPrwx4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:52:31Z"
    mac: ENC[AES256_GCM,data:GqwdimPtwqdT3iVlB4A+P/lC1Fmn4tTEIJqZOcaxHJZD5bLyM4fBT6dp8dIe5xKEnGwdw+xRAgQftRpI/OkchAQZtsolTrcdI5tZLHq/k7clg13i22vgfiYrPiY1e0jRS0jWz9VgdBcv8g7pp/VIT8jW+ej1Z1lPS6r5l+VlndM=,iv:iBFQNqLwNYH66inn99QQ0snbVLkKORmIxTwxi3Ch/Og=,tag:zvAzzc+lGhpWGI1B2DMjkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
