---
apiVersion: v1
data:
    HOMEPAGE_VAR_GRAFANA_TOKEN: ENC[AES256_GCM,data:XiQVTBNGiZAPPDS7eqXhZbHj32aSUo0EbqPHgGZJ9dY4qaQ5Hz+ztVffVc+qGfUSu49Ur0VnBzc0+WeGuzMwaA==,iv:XF/41ZoyBublCWKJp6mBPkPsKU5WjcK8kBY2H4lEuUU=,tag:QUcyiDDqXwBrLt36bvtSCg==,type:str]
kind: Secret
metadata:
    name: grafana-token
    namespace: homepage
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK1A0R2xWc2Y2RGJUNUh3
            bGlubTU4cTBDckVBL2FVamZ2Ry9CTm90am5nCkZGTFI5L3lTQkZmblVIUm1nY2pn
            Y1FaRzY2RkZUNWdJYmU3U3ZOTHVyd1EKLS0tIGQyUnB2WlFuTG1ubDlkeGlXVmli
            T2Zvc25vTlNQZWRlc1NkUnhqaitaVTQKgmWqmu41jQyEVmCZD1yDlx+WPjM+tQDR
            FHb08ODP8QXjPofYZ4qgK9YlItL6QMty158Uvxw/gzD4utlUbIemvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:45:10Z"
    mac: ENC[AES256_GCM,data:aCD06DbL5VF/swmVXqUw+q8Lp0tUYP6AEPVfyK8xHBhRceIR6wBie8iLCIoK1f0yMMxFF5LGg2IWAt2Yo1Q5Och7At06jHrIuutD5+xc1ol6FrMOrK8pewwIuow5Z0KGZbTKclCpKK9uBEziJdv/0ygAWZSzZE4j5tAGpml1YN0=,iv:zmoQGlRjbOm26DNyuG+iOIkegvR5hXVYKZwPZS48HEM=,tag:yO5/vCbymMJlIAAjOoqsDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
