---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  storage:
    size: 5Gi
  postgresql:
    shared_preload_libraries:
      - vchord
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector CASCADE
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-db-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-db-store
  namespace: immich
spec:
  configuration:
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    destinationPath: s3://immich-db/
    s3Credentials:
      accessKeyId:
        name: rustfs-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-backup-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-backup
  namespace: immich
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: immich-database
