apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../base/immich/
  - ./database.yaml
  - ./datastore.yaml
  - ./storage.yaml
  - ./route.yaml
  - ./secrets.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: immich-values
    files:
      - values.yaml=values.yaml
