apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TrXdbI5ws/Ik+CtNcHrfS2/duM6jFIHmlzSmwRfT9ssoCC0Vf6Bcqi9O2Y7T/Hl9E4igFlI7BR2Hc0o/agy3lXD02Q7+5xxUHCX7+Y2Kpd84rTej5B8MqQ==,iv:5Zln9bN/yVXf2hrUCeEf0AnyLmavPbjZRouafq04DAI=,tag:Yaj/7NgneOZrBEH2oAl9vA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:72Wwt6H7l8xWt96JHhdgGVGtBR9HKan2kLxS6M2vk9aDICJFm+00vchouRjsGiJSLrsAnRz2uJzF10SX02QlpAHjOAdCFnlnbYK4NxxftL0aEwp/lHuGIg==,iv:WkNfBoH5+nDtXkpX6WgiAtAmx35n9HLNRhQhaflmYyA=,tag:fArRWu2EekWpfZODJGI4Rg==,type:str]
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: immich
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cHppeTUvUG5rVFVnZmVi
            VmQ1ZTdwdVZOL1FNTHJobXB4MXpZRUZxUXd3ClRUTXFSVzFETWFBNXU4RDM1Z09V
            emxnRXZvbmttMGd4VzZpRmQweEdJV2sKLS0tIEFPa2NCTWJiNHIrVTM0cnBrV1Va
            NFVhVk1DS2RGeVY3cEx6UzdTSk1QUXMKdyrMcNacrnU0OZUgzDyHQZRNpA382hY3
            +2aAJFOJrHmYSgNCGAlMfSlEqPRMI7MrR/wlXSXwp93wH0j5PsW20w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:59:40Z"
    mac: ENC[AES256_GCM,data:rnLU/F9CgXib0+ChCMukN3ZW7p/5z6qSq1i4UBhmhXq1OODlGQIA7yk49JZeag7PJjRSX3L8V2YIHL498uSZPJSHdHS3zcdF6yIIH3YpiquoLT5s5pI87aIRgiesv6CTstGG5nkG7M7VCblj7iWorBoRChFc2Sx+vYyJLCUtXlU=,iv:geY0vvxJGqBeS+wi5XIJuSCMT63mdFWL2ax3VgAuEfc=,tag:fovYvxL3itfN+m0BgJwgBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
