controllers:
  main:
    containers:
      main:
        env:
          REDIS_HOSTNAME: immich-ds
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: host
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: user
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: password
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-database-app
                key: dbname

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library-pvc

machine-learning:
  persistence:
    cache:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi

valkey:
  enabled: false
