apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-operator
resources:
  - ../../base/hermes/
configurations:
  - ./kustomizeconfig.yaml

configMapGenerator:
  - name: hermes-values
    files:
      - ./values.yaml
