apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-cli
  namespace: signal-cli
  labels:
    app: signal-cli
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: signal-cli
  template:
    metadata:
      labels:
        app: signal-cli
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: signal-cli
          image: bbernhard/signal-cli-rest-api:0.100
          command:
            - signal-cli
          args:
            - -d
            - /home/.local/share/signal-cli
            - daemon
            - --http
            - 0.0.0.0:8080
            - --receive-mode
            - on-start
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /home/.local/share/signal-cli
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: signal-cli-data
