apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 3
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-db-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-db-store
  namespace: authentik
spec:
  configuration:
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    destinationPath: s3://authentik-db/
    s3Credentials:
      accessKeyId:
        name: rustfs-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-backup-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
