apiVersion: v1
data:
    password: ENC[AES256_GCM,data:YFjk6wEQilsp7TK84lxOs3DaFKQvgBngqkTIWdarwaC0TqefkxxG+6aXahqxLdkmvhraZ5VR67xEs9b5tSANkxvll1R51gkh5BGFSSHAb+UwKbb6kYDPmQ==,iv:U3MtRR5p1KUQ2U2duFtIj0KJzKcvM1cGFNCSKwB45I8=,tag:5vz29Ik3gaLCdOxQaeHOzw==,type:str]
kind: Secret
metadata:
    name: authentik-ds
    namespace: authentik
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eWtmbGt3V0VqOW5Eclp3
            N0ZMam90VlZOeG9IbmZXNTdOemRxdkgwcEVBClZPRlpVRzNXZ0Zsd3RxdFMrZzYy
            dWs1dXBYdmUxRUw1UDFmdXh2cTM2cTQKLS0tIEYwRURMbCtZby9QWGxLajIvVTF3
            NWJSb2Z2SEhBUWlBVXQ5Wm9CWjlHbjgK63dNsWzfDzPbYTSRcUhfVxdMh4Dk1zvD
            jFw8rf61vS8a7e1rILpuyH+lx/LIQCzc79T0to3L4cQzFwHrcSChqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T04:51:09Z"
    mac: ENC[AES256_GCM,data:y/ApNRaQNEhhx2IBRVbnInesyeJolIyA/mwmAjrP9Trk0S7odEci0WM/fLxNbWjJFHmcBYiwkA0x6kg8ui3tYHLFthheEKpoURO4DHA/YLfAfuAuofiGz95qMFFrMp+D9AEtBgi8VQ5gu/KI6A6ImBPMNfiNyPYZAZnVqiEOjzk=,iv:tz7E/nu+BDiPf7P5IEzKH+iRD7jGFvl/5Jbov3Dz2Do=,tag:2UlUfIeYbXbjoOE0+K3bDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
