---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-sietejoyeria-env
  namespace: wordpress-sietejoyeria
data:
  WORDPRESS_DB_HOST: "wordpress-sietejoyeria-db.wordpress-sietejoyeria.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress-sietejoyeria"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_TABLE_PREFIX: "wp_"
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', 'https://sietejoyeria.com');
    define('WP_SITEURL', 'https://sietejoyeria.com');
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
        $_SERVER['HTTPS'] = 'on';
    }
