apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/wordpress/sietejoyeria/
  - secrets.yaml
  - route.yaml
patches:
  - path: patches.yaml
configMapGenerator:
  - name: wordpress-sietejoyeria-env
    namespace: wordpress-sietejoyeria
    literals:
      - WORDPRESS_DB_HOST=wordpress-sietejoyeria-db.wordpress-sietejoyeria.svc.cluster.local
      - WORDPRESS_DB_NAME=wordpress-sietejoyeria
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
    files:
      - WORDPRESS_CONFIG_EXTRA=wp-config-extra.php
  - name: wordpress-sietejoyeria-php-ini
    namespace: wordpress-sietejoyeria
    files:
      - uploads.ini=uploads.ini
