---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wordpress-sietejoyeria
  namespace: wordpress-sietejoyeria
spec:
  parentRefs:
    - name: https-gateway
      namespace: public-gateway
      sectionName: sietejoyeria-https
  hostnames:
    - "sietejoyeria.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: wordpress-sietejoyeria-svc
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wordpress-sietejoyeria-redirect
  namespace: wordpress-sietejoyeria
spec:
  parentRefs:
    - name: https-gateway
      namespace: public-gateway
      sectionName: sietejoyeria-http
  hostnames:
    - "sietejoyeria.com"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
