apiVersion: v1
kind: Secret
metadata:
    name: wordpress-sietejoyeria-db-root-secret
    namespace: wordpress-sietejoyeria
data:
    password: ENC[AES256_GCM,data:vsrk4YyR9scKOVly2VOYoUaEoZYfDJesilwQlPgj4gtaH2Gxpr/I9hGyXZk=,iv:CSMO34tjcdRu09l4wp+d2XEBHhRCT+J00aRTXzTe+30=,tag:aOvDLzC5LC/U5S9VBOz6Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUEwvajR6cEx4d3JZQ1BG
            Skg2VWdhRUFuSWJNdHB4RFhDZVZpaWF3QVZjCkJJSURVM2JSbzJUNGxYeTBoUHRW
            RHdmZitKUkFsSktJZDRrS2JIZkV5TTAKLS0tIHRoM0VEU2FGVGx2cXYrY0VSc0J5
            K09pbThvdnVidmx4WVBzUklQT3VWN0EKnQo+ZAsLCNfbVr6ZFS0ka2Y54zstRH4K
            p3N7puJnd5kY2fQgBNkuRW3dIit2ByCghsUF1Q2F4WXvzCAILQ0RCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T17:11:38Z"
    mac: ENC[AES256_GCM,data:TJHDolvLAVQC5OVsxvJuAQtQu73E6c5CeKjTljwQN8a3D5kCrboJptPRSof3CeYeFPWVxD597lUqiAInyuh2JpNwD63rC6CTBx4bMjW52O2ZZLixAegcfcb4THxZEXpcxVbgzX5c+L25Wyzkn03CGFYVKCSkyMgJj6OfUXwJyBE=,iv:GUSAUaHDHlpJgl7uWmgmj5+MQASlFW+4Lc+ZGP2bGXo=,tag:tQqnyqn2bO1MSXfnkNAMrA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-sietejoyeria-secret
    namespace: wordpress-sietejoyeria
data:
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:hC4fcW9pOtjOtd3A40N8E3EiwPqO/wlKwCxsqtr321QK5YXkDO629/DC8S8=,iv:5ALu+t5eluRZooPyVcsNAmJeys412lgbUNLseTeQbnA=,tag:wVqVXaXhKzYFFGbGvQ5O7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUEwvajR6cEx4d3JZQ1BG
            Skg2VWdhRUFuSWJNdHB4RFhDZVZpaWF3QVZjCkJJSURVM2JSbzJUNGxYeTBoUHRW
            RHdmZitKUkFsSktJZDRrS2JIZkV5TTAKLS0tIHRoM0VEU2FGVGx2cXYrY0VSc0J5
            K09pbThvdnVidmx4WVBzUklQT3VWN0EKnQo+ZAsLCNfbVr6ZFS0ka2Y54zstRH4K
            p3N7puJnd5kY2fQgBNkuRW3dIit2ByCghsUF1Q2F4WXvzCAILQ0RCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T17:11:38Z"
    mac: ENC[AES256_GCM,data:TJHDolvLAVQC5OVsxvJuAQtQu73E6c5CeKjTljwQN8a3D5kCrboJptPRSof3CeYeFPWVxD597lUqiAInyuh2JpNwD63rC6CTBx4bMjW52O2ZZLixAegcfcb4THxZEXpcxVbgzX5c+L25Wyzkn03CGFYVKCSkyMgJj6OfUXwJyBE=,iv:GUSAUaHDHlpJgl7uWmgmj5+MQASlFW+4Lc+ZGP2bGXo=,tag:tQqnyqn2bO1MSXfnkNAMrA==,type:str]
    version: 3.13.2
