---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-pg
  namespace: freshrss
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: freshrss
      owner: freshrss
      secret:
        name: freshrss-pg
