apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:WR7tAWg9/rFJM5cdItiEd0oPBYc3Jf308xsidl4EkRXMb/Ify0bpYrlUUvOftpnlkpXukJx5s70PiHVVmglZx8jupJVxjjHjj0tFaJkZXfhnv25zj+sZ8g==,iv:74iTQmXE8K+3vhBdY5EeSGdeHcYm7pgUhuVPjO7gaxw=,tag:cJhuem5f4u+MJ+7TgIhs1A==,type:str]
    DB_USER: ENC[AES256_GCM,data:8G64EY5qF0liDQe6,iv:2jxwoGQgkiO2bV5JPAxUNJeRLYaqSbJehMXMVI/MZgc=,tag:03IrNkIzBKe8BK3H2zyrPg==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:AMQZ4mTFs5Gi0DXH3a6y9AXt/4mVhmfene3BJtUppkYnwsLSlZecJK5p2vHqfLVa9dUx32vt8TTiXEZLQRqeH5HIL57TtSyj6W9P0+06KFblIrFNia22ow==,iv:R8I/GGEZXbQM4WbbSorIHUJoFpX/BDZUX63ZDEr5t5w=,tag:CrgCCwXoz1ZYllxUfIRWLg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:3F2gIEWPKkI9qYOcIzQlUcWjeybWon8N4ySftRU6wVpWK4jwPe+MSdIW9TIDucScYU9g0sTVCAI=,iv:9Ws7+dZs/YPqm79zoNXqUkPwWG4pT+uOorYnopE6n10=,tag:rmPDuw2scBXLtdhm04XDsw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pG5RtT+I3lIL/koeIuH7IwO/zQ1Lj1tK2TNbtx4Mpnboy0nZqaxlNP8baEuHZ+iYjVTaa1vIexcg65THG0dyE0hZNSQJ8WQTvmYl7WD3vBF4p91P6oBeFw5Jn+xvDnwYkVegHFj6jgtrEYj8+HQzStHK8niMxT7GHxzETLe7yHhBM2NxG695pvfUjk5v0SvpQski7zgNg9pQH7jb2MKua4pm0gjLQJyQ+D7s+A==,iv:kf3luCkuJGzqhwOCOX8HF64PY7D/50/30SH+kYgkBvc=,tag:547mIUjylHuLp/CdcC9pZw==,type:str]
kind: Secret
metadata:
    name: freshrss-env-secret
    namespace: freshrss
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNGJVNEM5Q1lzdkZzRUs2
            SzdKNnd1VlBhMSs4TUZ3eUVSRWZHMzZXaVJrCjUzYnJQeW1xaDZUbFozLzg0OWt4
            TzdSdjRwSlBzK1lhdmJEUE9xcDAxMzQKLS0tIFRwOHpZOFJlNUk0dFFjSTlxK2l1
            cXh4WUZqcWdHT2JTT1ZyUVE4ajAzSGsK6ucWm6YV3VV03jjU/45IvsQTgXEGmL8L
            WDdHBLhH+5DMlIjbES++mZRzt6wBNCOnk5dNLiJo/cow/Lwve6DHhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:30:10Z"
    mac: ENC[AES256_GCM,data:yt7Xem5Wn97WOM7DiXnAjU8vvqPYlQ8da15vb8lG0i9n+0J8qZyZlq0zU+ikWKSBId9SePNLana4kYXiLscXXkFIjDVzaUFSCPFQ/dpcYFfupQjLJi5qHUJwdV5Tc54v/k1MggCOL9g5ZmCbI8KZeZAZ9WignvShmr7Z/LkS710=,iv:+7AaLZ+7CaBLgLfmsYWpys3jOvztRQnj1ok+04woYtg=,tag:7mwl4c/3lpoRbTUqUV9bLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:96npGuzZuyWUUNVE7uKLg6cbwmeJP/IGx0entSL213SDHXd7GJobxoFEHo1RPki2WaTq9TpE3SnN1qcFRiamwjFGxO9KOYM82MdtTzVKJMil2aou0JN8mg==,iv:b5QfUjoLtUCCEU++AMjNSfZ9igy6XwHRlbHHdZ1SZmk=,tag:pao3edFtMnZT2Oa3pvWcDw==,type:str]
    username: ENC[AES256_GCM,data:KSsM3hhcxldWUhGx,iv:G8c2qpjWjnsmehvwhQVzgsDvHX5MJPnbHUVpP62eh6c=,tag:Wc8EyBXTVh9eOvCLr3wVxA==,type:str]
kind: Secret
metadata:
    name: freshrss-db
    namespace: freshrss
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ3lNRWxQTzZLNWRyNG1w
            ZU9kOFRPYlNpdDY4QVZOQjN3ZmRwUU9iYnp3ClB0akRiQ3k4Y2UvMU13MU9pYlB6
            dy9VYTJNMkFXYndEV3YwWC9LaHord3MKLS0tIDZuM043dGd0MXM4NEYwQk1QRGUw
            R2dTR2tyN1RnWGlrMHVGZURPQWU0ejgKRkfbGXz68tY0BPJs3sInYwHmLdwNOGOm
            gkwXA0gtwpn5mESHFzVFPrJCE/96QZJGCvz7B69zVbfbwM30zEpK+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:12:10Z"
    mac: ENC[AES256_GCM,data:LRZBruMCFd2/ZamSEIQ/+Vvw/jIvt87BuNIVOmOaL77dmIMdtfFbL3NIht7UW7NkYiLoaUDF3lYU2qOkEjkz1Pf9MQyHCogDcHHlB3KXfegUcEjlo5EllZFRMHEejBFx50TaY6U/88nAIxhX0rdhXu1UifvLO+UKqVq9EvZv3ZU=,iv:AqGpS8M89gMrbE5su1R/6D46gbTsXjzeXtTz5XUb0Ds=,tag:j8JajeD91K2BMQuDU7VA6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TrXdbI5ws/Ik+CtNcHrfS2/duM6jFIHmlzSmwRfT9ssoCC0Vf6Bcqi9O2Y7T/Hl9E4igFlI7BR2Hc0o/agy3lXD02Q7+5xxUHCX7+Y2Kpd84rTej5B8MqQ==,iv:5Zln9bN/yVXf2hrUCeEf0AnyLmavPbjZRouafq04DAI=,tag:Yaj/7NgneOZrBEH2oAl9vA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:72Wwt6H7l8xWt96JHhdgGVGtBR9HKan2kLxS6M2vk9aDICJFm+00vchouRjsGiJSLrsAnRz2uJzF10SX02QlpAHjOAdCFnlnbYK4NxxftL0aEwp/lHuGIg==,iv:WkNfBoH5+nDtXkpX6WgiAtAmx35n9HLNRhQhaflmYyA=,tag:fArRWu2EekWpfZODJGI4Rg==,type:str]
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: freshrss
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cHppeTUvUG5rVFVnZmVi
            VmQ1ZTdwdVZOL1FNTHJobXB4MXpZRUZxUXd3ClRUTXFSVzFETWFBNXU4RDM1Z09V
            emxnRXZvbmttMGd4VzZpRmQweEdJV2sKLS0tIEFPa2NCTWJiNHIrVTM0cnBrV1Va
            NFVhVk1DS2RGeVY3cEx6UzdTSk1QUXMKdyrMcNacrnU0OZUgzDyHQZRNpA382hY3
            +2aAJFOJrHmYSgNCGAlMfSlEqPRMI7MrR/wlXSXwp93wH0j5PsW20w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:59:40Z"
    mac: ENC[AES256_GCM,data:rnLU/F9CgXib0+ChCMukN3ZW7p/5z6qSq1i4UBhmhXq1OODlGQIA7yk49JZeag7PJjRSX3L8V2YIHL498uSZPJSJdHS3zcdF6yIIH3YpiquoLT5s5pI87aIRgiesv6CTstGG5nkG7M7VCblj7iWorBoRChFc2Sx+vYyJLCUtXlU=,iv:geY0vvxJGqBeS+wi5XIJuSCMT63mdFWL2ax3VgAuEfc=,tag:fovYvxL3itfN+m0BgJwgBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
