apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:yhYqDB3/EnvBruI5Wfp3Pooio3/G7a0Q5Xtth1W6N61B7P2Oy7IWVCDDca4RWoN2qML5OV8VTh6XStkGvgO9QpxsOSEML3pipPiTMggff/KuZjBAVyuxVA==,iv:gcF/70EsOLkCzCKM0rVXGpg6QwzY3lB8aNrg1UwJXDg=,tag:ZBU3URNxdvnjsjZ7fHw0sw==,type:str]
    DB_USER: ENC[AES256_GCM,data:Fm4TBWBcNQ116onl,iv:zBE8npAvBLuPGaLapvEIuq58Ey6P/MHZyKglhM1jqfQ=,tag:sDTadU9EIJAT75AUXzuHUQ==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:G9EXQzH+v846kuX5z1pOF0fRE0suqPwHDkIeDDX2CeIOaMK2e/X2KE+qEfAaeONJfusRL2o8MbuceOrNKATgzz+RooGP+TPj1BRzJM39ha+67ARdMX9CiA==,iv:A5rSbV37L9EGcDuSRHXnYSw40r21yt6NcI/xhhyw/Fw=,tag:FCl3jT07uyGU0+TaaC4nDQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Lv2RShMyC1MFD8tilInCIY4HxjE2sB/6jJC9SuoxHDnCilD2U/KvvmTXJ6sE/giqOD0CBZVlIc0THtJeaa28DOxyDsT03UzjoRApvCvloywtssTHNCHzC2Ar480okJvKfgK0n8BBBV9VhFl9dq4JgnFGJvCskz1QteNlCDMWWHogGXyClSoSkanQncIl653zSnL0DXyhRJy/D3w4nvlLP0R62bE3JXJnEvk+hA==,iv:1LuSmxyktMFcjm0P6Qk8qhjg/C7BGrVQPsq7uqyHEBU=,tag:ajFNRcJcjzlYv1hnUgd3AQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lvzujJMv5fjiB8EHX8H8psKk3qcLEK3horjcKzFzvkMZfFxHqZpQ9gMWAAPKfpnnOeQWGWof+d1yXBdErc1bLVe+4mJhxbYG3kHxr1n6X2IiOTzSIYJiXhyVO/VDvqR1XcvHqQE6ky7rPzNZrMWzouaA6mofV59fhXycjwvtBdrMJl7KinJdYzbW/MhgM3Ie22qLN8uVAj+Ahfbd/ReUmmVKF+HVluMvrSZh7g==,iv:+mRj1XfB6wncFZl6g4jAWH2/wvseK2uit3LiCHyNBdU=,tag:Smw+WhA9U75tjI9Vo6ClKQ==,type:str]
kind: Secret
metadata:
    name: freshrss-env-secret
    namespace: freshrss
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTFJNlNwdm5HQ0t6RzBK
            emRHNXljU0dnVDliT0ZYRENhZFI4NkZZVEIwClVkai9KWGN1T2pPZ0J2UkZETmZr
            dExLV25YcmRReGE4MjJROFlCLzMyNVUKLS0tIHhaWEtNQ293RFd4cnkrMG5yN1Fn
            WFlXNGZwNjFqOFpUaG5mQTd3RUlqRm8KjAjZif+qGWO9LjzORKXvA8RZqr8/VkDc
            LsIjw/u+wQBtyfCFlfyDarnS2Kb08BNus8bDLwHPbg/m2s9BP9F0AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:56:56Z"
    mac: ENC[AES256_GCM,data:5tJTcDNIze/Lxl0CpHVRS/1+AxvTd6GZ9ktfcvbzx71aMuGl1URwEsV9k4FGG7IgY//oyRi2S+ka/VVr0CeyEgOhw+cpUYTlOjw6qTHiAvdtKt223wgRYZC9G9FrCUbjAA+nx/TfkpMb8FGT58kriatwPbymdBI7nnSyUuYvruA=,iv:DSAapVDPP2xmTRnmUTrNV/tjtFH/y3UnYRfJrcNhMsI=,tag:IGoeWeZS+Byl1Sgua+xBmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:96npGuzZuyWUUNVE7uKLg6cbwmeJP/IGx0entSL213SDHXd7GJobxoFEHo1RPki2WaTq9TpE3SnN1qcFRiamwjFGxO9KOYM82MdtTzVKJMil2aou0JN8mg==,iv:b5QfUjoLtUCCEU++AMjNSfZ9igy6XwHRlbHHdZ1SZmk=,tag:pao3edFtMnZT2Oa3pvWcDw==,type:str]
    username: ENC[AES256_GCM,data:KSsM3hhcxldWUhGx,iv:G8c2qpjWjnsmehvwhQVzgsDvHX5MJPnbHUVpP62eh6c=,tag:Wc8EyBXTVh9eOvCLr3wVxA==,type:str]
kind: Secret
metadata:
    name: freshrss-db
    namespace: freshrss
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ3lNRWxQTzZLNWRyNG1w
            ZU9kOFRPYlNpdDY4QVZOQjN3ZmRwUU9iYnp3ClB0akRiQ3k4Y2UvMU13MU9pYlB6
            dy9VYTJNMkFXYndEV3YwWC9LaHord3MKLS0tIDZuM043dGd0MXM4NEYwQk1QRGUw
            R2dTR2tyN1RnWGlrMHVGZURPQWU0ejgKRkfbGXz68tY0BPJs3sInYwHmLdwNOGOm
            gkwXA0gtwpn5mESHFzVFPrJCE/96QZJGCvz7B69zVbfbwM30zEpK+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:12:10Z"
    mac: ENC[AES256_GCM,data:LRZBruMCFd2/ZamSEIQ/+Vvw/jIvt87BuNIVOmOaL77dmIMdtfFbL3NIht7UW7NkYiLoaUDF3lYU2qOkEjkz1Pf9MQyHCogDcHHlB3KXfegUcEjlo5EllZFRMHEejBFx50TaY6U/88nAIxhX0rdhXu1UifvLO+UKqVq9EvZv3ZU=,iv:AqGpS8M89gMrbE5su1R/6D46gbTsXjzeXtTz5XUb0Ds=,tag:j8JajeD91K2BMQuDU7VA6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
