apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin
    namespace: obsidian-livesync
type: Opaque
data:
    adminUsername: ENC[AES256_GCM,data:pzfCjIAL6hHTdTPF,iv:J262zyTLO8PPz4SL81cfNaqOw7Xz/e21O/9tzUfluvw=,tag:hQYpyxk3HxGGddT/ueXsRg==,type:str]
    adminPassword: ENC[AES256_GCM,data:DRH0IxtmyOm6xhKrEoS4Aye5QLlQ4zVN6i7rnXDMNQqoz9V4bdgEbjM0xjk=,iv:62yX9FhO8sJb06WANyz2GnMgCYPCkPo9HN+89WF8Dl8=,tag:4ozdj/9+ZchLgVlISW5tiA==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:iHE3a2K/XoiioWnKwKGPmXw2sSFsMi354q5tCs6HH28uZzccu46BXb/VacU=,iv:Dcut7L2P5dIkguwO9yz/SfwsUGL65BzCgkcW+bUwX88=,tag:/yjb4ogOW8GaAtJetmjuCw==,type:str]
    erlangCookie: ENC[AES256_GCM,data:pKG9bFXzdX8cgTNmJ2IAJYe2Q9F4vSirp+UVySmLoSW3MuxkorQPbl0KsG4=,iv:ldW09Mhu4aUV/NkQiUTWdvLONe0RQuGknSeQuS/noxk=,tag:pZHLGzcJtQ+B+9HQvm3fiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEamhlNTMzejhHbHJBQVpk
            YUxVSFpWS0pMdW04c0haY1pTWEV5WXF0eVRBCjlZZHJXd2dPYjdTVjZEUnJ6Ym9Z
            YlBrUW04djFwOUs2MzgxakdxKzlEYjAKLS0tIEVzL1dPU1VidHZvdkk1L0FZam9G
            emRxeWMyaDVaSHNyRDNvV2dyREZnMzAKBNX+hwiVdyZGAmvud0ETRBQtlNqujANJ
            V9fHAg0Lm/q1j/QjTInKvI6WiGiu7L8olDDxVX5uw262FV3ZoZCJsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T18:39:14Z"
    mac: ENC[AES256_GCM,data:DF497uoRzqmG2CNu8nnbB34SjWr/NJrxJiqyP3C8c154w/ZndjPq/d3LUKtVCCxwQkuQX340Mrq1Wpd+RIn7NcyKlpvv+TdYs31citBH+yvF4qENxIOS9xdp2n3J5zVTemgOD9oZwAA4N8aJga0klWzBuJGjcW4sXYHJhb5BrmU=,iv:lFVzE2zYvIcUddT4hwFUG35ShryWcgLxYb9EpFTHuTQ=,tag:Z1Iy6AXeSucvCX3zvzQrPA==,type:str]
    version: 3.13.3
