---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grampsweb
  namespace: grampsweb
spec:
  interval: 15m
  releaseName: grampsweb
  chartRef:
    kind: OCIRepository
    name: grampsweb
  valuesFrom:
    - kind: ConfigMap
      name: grampsweb-values
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: grampsweb
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
                value: 60
              - op: add
                path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
                value: 30
              - op: add
                path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
                value: 30
