---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: 1.16.29
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: n8n
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yaml
