apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      #securityContext:
      #  fsGroup: 33
      #  runAsUser: 33
      #  runAsGroup: 33
      containers:
        - image: freshrss/freshrss:1.27.1
          name: freshrss
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: freshrss-pg
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freshrss-pg
                  key: password
            #- name: OIDC_CLIENT_ID
            #  valueFrom:
            #    secretKeyRef:
            #      name: freshrss-auth
            #      key: id
            #- name: OIDC_CLIENT_SECRET
            #  valueFrom:
            #    secretKeyRef:
            #      name: freshrss-auth
            #      key: secret
          envFrom:
            - configMapRef:
                name: freshrss-env
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data
