apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - image: freshrss/freshrss:1.29.0
          imagePullPolicy: IfNotPresent
          name: freshrss
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
          envFrom:
            - configMapRef:
                name: freshrss-env
            - secretRef:
                name: freshrss-env-secret
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data
