apiVersion: v1
kind: Service
metadata:
  labels:
    app: freshrss
  name: freshrss
  namespace: freshrss
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: freshrss
  type: ClusterIP
