apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-agent-ramon
resources:
  - ../../../base/hermes/
patches:
  - target:
      kind: HermesInstance
      name: hermes-agent
    patch: |
      - op: replace
        path: /metadata/name
        value: hermes-agent-ramon
