apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-ramon-secrets
    namespace: hermes-agent-ramon
type: Opaque
stringData:
    ANTHROPIC_TOKEN: ENC[AES256_GCM,data:9uaqFBgajjTc6eoup5GD2aghDkmq2bjrRMFzUbXk9VHd1093KewZTlKdufF4ETNyaCjLHCdwRKtXXLSz/eWd0M9fFXb2VvQ5JQaX6hSSRoeiDKzY1cFHMx/U8K9AzYMwrE57RTuFDg0DdjAU,iv:zUPAwCsLVCWKmqPK5/cUaw18L6aapJuDB1zUF+9NWsc=,tag:AetSFJ4a/zxSMmRfLf4/+A==,type:str]
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:K/BS60Ggglyn02uc,iv:FglcfblbqIOiQ82+/eGEx05Z9P9Fp6xww3lzx1/mTUw=,tag:s8tkiBGzs+RR4FqlV5wdiA==,type:str]
    SIGNAL_ALLOWED_USERS: ENC[AES256_GCM,data:qqHPu0+P2QOeLFW1,iv:LCBwFl6s5jjSazi/j0H9VOYwtZn9v8UK2wnJPtPcPHk=,tag:qBS9R4R6vsY8D8Ph+290ag==,type:str]
    SIGNAL_GROUP_ALLOWED_USERS: ENC[AES256_GCM,data:GD4bb/ih34DBUfQvLI1z1dZQXo+etADS2ERIJgNidY4I/Sh2U2XEnZeIcow=,iv:QZlCd/+0hPBGwS1x7jwV+AqmZRB66vMl1RhQJGN0CpU=,tag:2hqV0XxodSbt/IgJ+vKvlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybmZaR3oraHd4dUcybEhr
            ZWtrT01OdnBMaDROQkJNS1kranVscjg0UFRNCllCcFRtaG5MakY5SG1DNkRscWNM
            ZHV5a21sOFFDcGF6UVZwWUd4OWRPVmcKLS0tIG1tVHV4UEpXZGZEY05hV0FzbWhE
            QnFFRnkreW90cmNZdC84UmpCbVdrb2sKVwiXpZdybrG8ShRdYjzMRysWjNIoNjbi
            euF+/m73tIJBuCgr22DrFoKk3ojMtmpP65vKjzsEVQZwZJcR+6n//Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T01:17:58Z"
    mac: ENC[AES256_GCM,data:AKFzq5FOw9DZeMTBlDM5yI35JmNOXN1CiXb7ZcERYH614UNwI6MrEmlGMOc5f3cJ4FrRJmzZS4BTtRvx+oJEOUhVKUcx/Ig+j02iAy7bEunw5MCbqT1XaTn3/w5G6i3EJqXej+4qViYClNHrHPmvWNrL9U8skNhXpQwLFjeHkEw=,iv:h817rBcjm3eQnoaSA1pJEo8DbXp9s1a/xpfrRk9/huo=,tag:ocjUUI5yjLwz6AjspLMUtg==,type:str]
    version: 3.13.1
