apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-ramon-secrets
    namespace: hermes-agent-ramon
type: Opaque
stringData:
    ANTHROPIC_TOKEN: ENC[AES256_GCM,data:o5E1VwEmJ4edMwNqmZJeKYG2HO8ScXJwLzQuOB9V62S+H4o5wkrGTfPNFgvI9J664ukXF2BOoCqhfIneu6SwZuDu2i1LYxXygfOYJd3Zr725czkex6f/oSTr/9WIkNCPlFLJoGNGO5es1ND4,iv:f2GFwwDo+RdfODh0HkKqI6GgZvYxFOt+p1X6w3A/gTg=,tag:IyMKaLaCvhH8v3PCts7Pvw==,type:str]
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:FIjXyKrg1vwuBcZZ,iv:n0WOrc1JAtoewy6uyfq9111uBe0j03cOVR9zkFGdtKU=,tag:qYjfLuhG0DMTHuOvsIoViQ==,type:str]
    SIGNAL_ALLOWED_USERS: ENC[AES256_GCM,data:qCFax6YuvE5hRuu7,iv:9yj7Qrnt3UMsvejPFdeByFmfCySSHcATLOpMRm3b2TI=,tag:GnsuJdgC0DJJB8DNJgBVjw==,type:str]
    SIGNAL_GROUP_ALLOWED_USERS: ENC[AES256_GCM,data:FjYs8eT5QKviC25HjLeS8HRc08G5zQnuaksbkqkA5EHo2PmPWH6eNS8Jl2g=,iv:EJVjyVELsp3tNYRWGhWy4naynN8Rl2fHg+9VYFIlK2U=,tag:VwlNvJ2TaZ6CSxMjilZZ1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQVJlZzFSTFg3RklrQ0Zm
            NjUwL0hKZkpIL0VTd1ZHTEVOS1hVRVlWQ1FRCjljZWxOS1hCWkpOTndjNS9KK3E0
            dWgrbm5RRlY2QXdMU3VFR0pwMmU2TkkKLS0tIGtCejhUcCtpOUplY0VGOTArTThI
            SlVLNzVFODlDQmFlNkJiUDVyQzdVV0UKLwrTT9/RGrPSimrxBGmOxY2QPnmWHYiK
            MhbmzT0IjGLM85oBKiVO5a45bo9+JL8zd1zeOZ69tqqWCkZmVvLHzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T00:53:50Z"
    mac: ENC[AES256_GCM,data:3iaMZkwmSPSIBXmkpRvRZyRrQiGCuMbypNefWTyXIvGTgiPswxzOwr0Asy3BqgvqgljXPXxqObfdJlSh7g+9uB6LX51JAPvp0pAhtM58LLc7eGNJcoU4v1cuSaSWWBvwupAQy0wrBtVL1TkzuicRzwAOVCQXHDWJ0JvvFcFnZBY=,iv:h9dcMVEieKEs2Ngc5ja0IqPKZF5rSEsyWbtbe6SqQII=,tag:AguZF2LVkxycqPeqWUNnMA==,type:str]
    version: 3.13.1
