apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-ramon-secrets
    namespace: hermes-agent-ramon
type: Opaque
stringData:
    ANTHROPIC_TOKEN: ENC[AES256_GCM,data:qUK4JLCVo6RsNeFwiW10AHfW2h/rs7QujMVt3aWluzS2hnYwgb/1JBpgyaGqDAMMbcMiVOOvXFIlCMBrQt2SOCgpJmA5ZIfMkuZCeJ3z9LbXBeLoCrX4gsZE6Cz76JgX9Ci+PjQu/ZpLwo3v,iv:6c6dLW3xhGJLad4yw/uir0otJBbiJ2W7bga7kEQAqUI=,tag:7z90tU/8YPWZjJfgYRbfig==,type:str]
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:0/h149PHXX8Gn+SA,iv:Aqn1v6mjhCljtFz02vg7oXtwd+4YjMiwfOP2gQxOFtM=,tag:qFm58JeI4N+ekXjoHNuaxQ==,type:str]
    SIGNAL_ALLOWED_USERS: ENC[AES256_GCM,data:ITy1xWqRP26XtKIY,iv:9MFshht4a5zQVwuiBu4l25MrPH1u0BEr1fuAEVD6g7E=,tag:ASonlC98NclO6vlUocq5sg==,type:str]
    SIGNAL_GROUP_ALLOWED_USERS: ENC[AES256_GCM,data:9tQLjiUkFqXG1DmHYPaZgMTCMyxQwrb2qj4v1emc1S2CakN4tqIu8TAgd7E=,iv:aFpZYnSAC8iFgiqRf3Uoay92eO/Y0MXOyxsMN84cOhI=,tag:m9zgdhIUR92BnyNqA54UPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ2hKTE94OUtvS0JDZUZG
            UEN0VUx4SWNiYk82cUpQK2NxZXRZTDBPbmxVCjc0Tk51UGpxY0RTZENaWHlVTkZY
            S0ZnNU5wM09kOSt4ZzIrUlN5ZzQ5MHMKLS0tIExTanYrNUoxem5UNFFOYzFRNXNN
            UVpFVWlNS3NCbk1JSDAyZ1lDNktiN2MKYdxAwVBBTlDoX7K6+qcFr3Wf+cURvlrQ
            5b5wCHY8jgeQs5B5j3UpeRjnl/ziPidYParIuGlCa7r4QigN2dRrhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T01:31:40Z"
    mac: ENC[AES256_GCM,data:+eHz7BxUbEOaC7oYT/AjOyEsBHQXyovZmCnOcdqcoQ9AoZWy4F1cPONrWlj/9hQAFpzbpZ2j6YdJ5uStKk1+i0L12SmrMzeoYXKEuCgw7E0Dev1T4jjm+xLSMjhXuosbjmk8uQaYb61mM3x73ric7xebwJP9Zd2DKdOhA5DBBis=,iv:r3U1nGe7clbVoIuqT8QI3jMdoS1lO8y5TWBvVw8jiUg=,tag:j8umBOsHyblFBpGRgPnKWw==,type:str]
    version: 3.13.1
