---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-sietejoyeria-pvc
  namespace: wordpress-sietejoyeria
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
