apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grampsweb
resources:
  - ../../base/grampsweb/
  - ./database.yaml
  - ./route.yaml
  - ./secrets.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: grampsweb-values
    files:
      - values.yaml=values.yaml
