---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grampsweb-db-backup
  namespace: grampsweb
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: grampsweb-db
