apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3ADZVJzo7fzMxNnKP9uWYUw+BCO4OWC+qmz04H3JhjhK3pj+KbKogIq71rwQhSpNzsz3g57+AIHS9rq8cOnVAYb3VTvC/eDh97IFiPHngAYHLn00RqBTNw==,iv:97EqMIDOOCuWxb9a2jKnAyMnnFjScQNZvfrmxFzf5fw=,tag:+mjXXKXbIVnIKpKXnj80Pg==,type:str]
    username: ENC[AES256_GCM,data:Z64P0moKnHBJo0d4,iv:bqO2VVqG/FrcQWMofY0Hr/Kh44TCRGAgg2ySfdR4cOc=,tag:/7TI/lSdr15ssMiHpIr13g==,type:str]
kind: Secret
metadata:
    name: grampsweb-db
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEl0aHNvVG9pa08yTlFu
            ZEdqU1V2ajBhUFdIaHRMVWJrYU1IbFJ2alZjCjIzMFVvSTFqeTV2L21JMVkwUHZT
            OThKemJjdmR2OWczQVBMdmdwMWpxbUkKLS0tIG5vT3k3MXlQcFczZHdjMEdFNXBs
            ZDZwdmxFdFhOV3BjR1RncnkzMVdOQVUKElo0EOw0RYD22hM7b58FAO1+ZGAvOeS4
            EFp1w6H7bmhvhpdLWGC5ORpplCDFOFqvo2KvEaq/EIRs9foDNN7KJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T20:52:59Z"
    mac: ENC[AES256_GCM,data:Eez2sx36x02gxsZx75k2hm696pMKIEt2kpg1Gi2HT9LxiyXA+EHBkrFkcnriP5zh3PgMptf09/wstvn0CbXGVONtycRz61oaN/QZz6P05ontCw/I9zC34yuDe29iqDEVeEe6NBM052joy91+WrmltehdhCOB+5XS2zgiTFrGu2k=,iv:spyV++l1+OX5KYWM7DZY2LTozPYOws0dBMcNFZ9C9T0=,tag:nJp2U7GTP5zEOz6UE77LWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    config.cfg: ENC[AES256_GCM,data:KPbqL7LicB71mJoHncxbqogNsCDeU/Sr24t8GgIYTh2jNFBtFHqeBF9oJnRVXB2O1D6CHSFkgbg2P+O49v6NDYghj7bvAwzb6GCD2O4mxKM56Wnlfn/AjNjeKY3nHEQLtKxFbhwrQb5nwxlDhGymU+z6tUE096EPlXTfPIW7aq51vsQYIo0Bl5HdEgW2L81A5meCh80xDtKLcGeD6dyIqWFzBz0yqHvbRpwJUQ1cG0xTDHb7+gembYQimptq97pDzCLbBiMwo36CbaJ5i+FdJbw0dP/zc/madHeUHwKRGL49WuyCUl27bpYDcIosTQHZE6nQzL9SLIBx5YlAnMAwQnlmP6QQ50Isg9uU1pleqszCv/hpnm5W5OYDGZkg49mEbeBOXZIa1e85uRzU7PcM3NA/rbREQ3PjvztkCkAafx/0vqn7dywMyBNBNeTKqbnADH2/+KZ6cWZfRXe1YE2AnP8+HW98H1cj3aac8ZI8BRSzfZ/mmwnCk5eY7y7jMvwP+SMaC7dL+wgO3GiLH+hMQQRlnS1oCITNsrtB6j4X/J4+u2/VsMHowIz4KN7pmxGoZeVAtmjWJb6Vj0UvNBELyAsvIGgnCOxcpKjEv9vCuVQMGo1V6C02epD8aWKrARMrXq9esa2R7x45C8WiA6R2I9HILuNMQv6IDnF/LSXwcFs4pk4l59l3iPli0AQScHrFJz6aT43KETJIuN0jHTEedQMh55q0S92n7ipF+i6L+2/BL+d7tEAbFl916awkRYJje7wJiH5OXExdQrnf0o1G5p4AO/5ueF6KFvPNWF1Xp2h8F+F+EsdOxTvKs3l8bXFOx764nYmXLWneuKBJKOrJe1SE9k63X3bGLFKoEw+9DFScWiJA8ZABYLxVUhII2sTH6lJrcIbhf08fr0C58D+vEji1oYbnZmdgvzPkXqYPMJfW7OZYFyVVb7I9wz8Qutjo92VqHSSz2cVD2b0T9ackOlUd69lW2z6f3aL1SL0zalq+9Tg1zYM/+cil4CM4LGRT3Me2YFo+o/Z358fkET20tax15rnhYkfB2XyPJuiVdjPS8iw8O81lJU1GEIPz/biOxzEYsiFE6H3hgtGSKG5ackG948NkclAyL5jS+Yes9dByuB2DZBDXbYhMzBW1YheS8pxkGUJQoWz+GrMnhqMfwBC+hMOjtURXzMNiTDHMZ4GfUA8hrxu2KTXAacLgvCFbHzpsawy1xAQt0cm9CGuC8OLnxHtIa1BwgfEomDxbJTKPhogti/XU91nifYtT5+rDEFEeGKab7aVacU/jfREzddB7g4g5z1AlgaqtVBH5yPRcEI8+FQ0vZ50RhN5+HI0tT6FSEhbNYThurvtTuixD+IWIT2pkhYeZZIaC3KVorDY=,iv:1SJo8NSLQNE3NA53mxiWLcoVAManlY8BzoKsawHj+q0=,tag:T66WJmlzssJlSsybbbwELw==,type:str]
kind: Secret
metadata:
    name: grampsweb-config
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEl0aHNvVG9pa08yTlFu
            ZEdqU1V2ajBhUFdIaHRMVWJrYU1IbFJ2alZjCjIzMFVvSTFqeTV2L21JMVkwUHZT
            OThKemJjdmR2OWczQVBMdmdwMWpxbUkKLS0tIG5vT3k3MXlQcFczZHdjMEdFNXBs
            ZDZwdmxFdFhOV3BjR1RncnkzMVdOQVUKElo0EOw0RYD22hM7b58FAO1+ZGAvOeS4
            EFp1w6H7bmhvhpdLWGC5ORpplCDFOFqvo2KvEaq/EIRs9foDNN7KJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T20:52:59Z"
    mac: ENC[AES256_GCM,data:Eez2sx36x02gxsZx75k2hm696pMKIEt2kpg1Gi2HT9LxiyXA+EHBkrFkcnriP5zh3PgMptf09/wstvn0CbXGVONtycRz61oaN/QZz6P05ontCw/I9zC34yuDe29iqDEVeEe6NBM052joy91+WrmltehdhCOB+5XS2zgiTFrGu2k=,iv:spyV++l1+OX5KYWM7DZY2LTozPYOws0dBMcNFZ9C9T0=,tag:nJp2U7GTP5zEOz6UE77LWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
