apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3ADZVJzo7fzMxNnKP9uWYUw+BCO4OWC+qmz04H3JhjhK3pj+KbKogIq71rwQhSpNzsz3g57+AIHS9rq8cOnVAYb3VTvC/eDh97IFiPHngAYHLn00RqBTNw==,iv:97EqMIDOOCuWxb9a2jKnAyMnnFjScQNZvfrmxFzf5fw=,tag:+mjXXKXbIVnIKpKXnj80Pg==,type:str]
    username: ENC[AES256_GCM,data:Z64P0moKnHBJo0d4,iv:bqO2VVqG/FrcQWMofY0Hr/Kh44TCRGAgg2ySfdR4cOc=,tag:/7TI/lSdr15ssMiHpIr13g==,type:str]
kind: Secret
metadata:
    name: grampsweb-db
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEl0aHNvVG9pa08yTlFu
            ZEdqU1V2ajBhUFdIaHRMVWJrYU1IbFJ2alZjCjIzMFVvSTFqeTV2L21JMVkwUHZT
            OThKemJjdmR2OWczQVBMdmdwMWpxbUkKLS0tIG5vT3k3MXlQcFczZHdjMEdFNXBs
            ZDZwdmxFdFhOV3BjR1RncnkzMVdOQVUKElo0EOw0RYD22hM7b58FAO1+ZGAvOeS4
            EFp1w6H7bmhvhpdLWGC5ORpplCDFOFqvo2KvEaq/EIRs9foDNN7KJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T20:52:59Z"
    mac: ENC[AES256_GCM,data:Eez2sx36x02gxsZx75k2hm696pMKIEt2kpg1Gi2HT9LxiyXA+EHBkrFkcnriP5zh3PgMptf09/wstvn0CbXGVONtycRz61oaN/QZz6P05ontCw/I9zC34yuDe29iqDEVeEe6NBM052joy91+WrmltehdhCOB+5XS2zgiTFrGu2k=,iv:spyV++l1+OX5KYWM7DZY2LTozPYOws0dBMcNFZ9C9T0=,tag:nJp2U7GTP5zEOz6UE77LWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    config.cfg: ENC[AES256_GCM,data:IYPm10oN98cVJ6qhBI+ZwwW6uRQ5WCoLEvW+EHHIRZJG3ytKWOOw7/9neZoCUgvlIeTzTJE0sz0Y+jz88DjxaBN1amrlNimj80vfMYXXOkcpI/3EGU+3aoSClS4K99093hALCm75pkH32DVzUvri7Gh73AV26I6b6TJQf8hrMTkqsU05n7gw2bn2pcVM4F7RDqXzNGapsL5yKl40SfXQXWX8OUGv5lRXL12BSBR4vqR7NTcrvig33nVehtp121uC8reSmlrDHNMbP3ur2KwgJN+W/Jw+Ezn3+GhjB4/sbiY7BEDP5QUE++5H+pBPDrqBxhArhnfWHAftX9h3GCyQdTFajx27QjA7qy4K2egjR/HfYMHs7JDV0Ip1VZi5rBeoaiWpmlJxVwWEZPnYkR/DdYWYgkX6BoeWAWXqFScPTfyAAEI1Li6IUKWaQBHoL18BY6Gw/HixUuS0JBdD8djA8SRjXGF6KJyVTu9nJNUB6ZB3Rh55Ft/KXzvvjaekOGzapw0jh1HER+g+c3yZ57fSSPADTmrhwDvROXxWda4hemymiQj2FfBPsDsXMFPo09+d1jgWr6C8DQqGth8/kdcI7EDgCwHoqwFYy1C0n8H4a3iiA2sY2hILHcqKnC7sYy2Z17dQFd5Rbqx+OaIf5QIYdCX98itZQwzAznHwFbx1U3m5c5JtWrdf0Cmdt4wxHUJP69K1wjpzugyrOucD1ydyIcAJOK8LtU+74pQDsz6PxI9cBU7jEBbMR17NHmj+yllQdmSeyEnEZEn0iE66FFqHWtP/aV/+JZu5HaAC/eKNpU9+TfEVvhIdYopq8znJynG9Hy9LV/BizhfwIeIkptvuYHSNFcDwWavKHeEr8aMYYu6m1Ibq8f+zwdijB11HrecizMtI0Zu3R4Ob8VuQsf9Pi+SAUG5zu0sQjqmgTi1cwNWZOTPjcnxVQTyCpyousI3rz4rr34QjVJKZjyJuysyadJ1V3Ea2PibleIr6VzoJ4MpICdxbLigHfkBxj4/iP3VKMxE7Sn8vAmO9WAHNTTJBdptjVzOR+VtWyjaRckTWgRcEYyj1TrU5/Y+UHoP/dDSjDzH8pjFFRaM0Ozpbt4xX4jClIkRBjE5EtMSZB1iHxDYCYGkU5HGwP/AjV20EQ1al+1gJfQNwwL4atH4VbCkZidaC1lbXqDk1PZHgnsRWS92Rh557tbQMaYC3e06KB/xqR5IkUsurRmsjY3WFxFeMWc7p8GViWLeHKbVMZAddUMu/J0ShxU1dLdnqcao5HM4rt5MpN0u9Rev/1ylnJSOcQ6FUHGspicOBgAqnvPG/mpYqrpHSVZl/bYQmQwNhYlL3WKC8c8lJ0HS07Q3S4OiBkGR/hqC6XG759vOs0c/hGmIUsjSniAy71ir/T2d1Z7JlbRb0whYbNHyFTc0mUka6y3zjLEjh6II1D8yw20FInKfi11iEnFZF+1f5SzNL9tIAXs0DmWtbp+fYXRE4,iv:yjMlsJV/dINdCgZB9snsNp6pkjo5VPSWSpB9m/uS4SY=,tag:1QMi2xd+pftrE6u5o73iHQ==,type:str]
    user-db-uri: ENC[AES256_GCM,data:+xzORJtJ5MvZanUy5NP7SGPRvbIYo3aDAqEj5V59X8Zzxw5p8OIee/a2r+f2nr+EW4FQv075uuxeMPhklJW7F78wXaL6mfWVTx1/c80hN8UpRhM2FsCadrj4R0ZqMmrB9KLTpg5MXgAb42MroUS6AiklH4W9c2YuyH5SBTUtPc/apwj51SzNUmAqLXCBrAxqGs5eQ+ew7wvf340j5Ab0eiOghnHKMlGegsgEf+Jsmya+aShz/p1MY0Z3X/bWNjCGnxQvgg==,iv:7Gl69+qrcnGyWTm5GCZbIPnXtK9iYA0mvjmF8jX6Zdc=,tag:hyj/hpT0fDnTyMLx+F2LSA==,type:str]
kind: Secret
metadata:
    name: grampsweb-config
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS2VINnBBb3J0MEs2RXAz
            NGdkdlVLT2J6cncvWnRYaitMdVNKRUZmMWljCkllK3F3bng0TkNTOWViVFRNNHd4
            eHR5RXdGWW16N1VmcHU3SVBHNTVkaDgKLS0tIDZBTW0zemRveExRdWU2OUdXV2h1
            WlBmdFM1VUd5aXdLWFdpTjFhWEllUmsKe12dDmlIjFroe3l43tXhyaFZSfTcKMiP
            tyjno69dCHJG4nEi6WE6nXekCTV8A2/v0SXL3LYACdTDPPFbKK7uoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T21:51:12Z"
    mac: ENC[AES256_GCM,data:s/w0kSwsgzFtfRL0KO1odv76S8Y6AEAdc+DL3NCBjof6gMIlW5XAQbSACsYntujhmrXL4Qry9LYNnAbiJQM7N8Fwq9SXpvmLbON7LQqAnxmKdtUurzBDxE2aM2clHXFdTw6HPVQ217GGzaQs/Y5GEc6pKYB70ZsHEUUtdcWf/XE=,iv:NryocIRv9bsV+q8MGhiBBBrjpk7OnmlLXv8sfj+LJWA=,tag:dN0nYFVI0jMS1iyzS6dcnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TrXdbI5ws/Ik+CtNcHrfS2/duM6jFIHmlzSmwRfT9ssoCC0Vf6Bcqi9O2Y7T/Hl9E4igFlI7BR2Hc0o/agy3lXD02Q7+5xxUHCX7+Y2Kpd84rTej5B8MqQ==,iv:5Zln9bN/yVXf2hrUCeEf0AnyLmavPbjZRouafq04DAI=,tag:Yaj/7NgneOZrBEH2oAl9vA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:72Wwt6H7l8xWt96JHhdgGVGtBR9HKan2kLxS6M2vk9aDICJFm+00vchouRjsGiJSLrsAnRz2uJzF10SX02QlpAHjOAdCFnlnbYK4NxxftL0aEwp/lHuGIg==,iv:WkNfBoH5+nDtXkpX6WgiAtAmx35n9HLNRhQhaflmYyA=,tag:fArRWu2EekWpfZODJGI4Rg==,type:str]
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cHppeTUvUG5rVFVnZmVi
            VmQ1ZTdwdVZOL1FNTHJobXB4MXpZRUZxUXd3ClRUTXFSVzFETWFBNXU4RDM1Z09V
            emxnRXZvbmttMGd4VzZpRmQweEdJV2sKLS0tIEFPa2NCTWJiNHIrVTM0cnBrV1Va
            NFVhVk1DS2RGeVY3cEx6UzdTSk1QUXMKdyrMcNacrnU0OZUgzDyHQZRNpA382hY3
            +2aAJFOJrHmYSgNCGAlMfSlEqPRMI7MrR/wlXSXwp93wH0j5PsW20w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:59:40Z"
    mac: ENC[AES256_GCM,data:rnLU/F9CgXib0+ChCMukN3ZW7p/5z6qSq1i4UBhmhXq1OODlGQIA7yk49JZeag7PJjRSX3L8V2YIHL498uSZPJSJdHS3zcdF6yIIH3YpiquoLT5s5pI87aIRgiesv6CTstGG5nkG7M7VCblj7iWorBoRChFc2Sx+vYyJLCUtXlU=,iv:geY0vvxJGqBeS+wi5XIJuSCMT63mdFWL2ax3VgAuEfc=,tag:fovYvxL3itfN+m0BgJwgBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
