apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3ADZVJzo7fzMxNnKP9uWYUw+BCO4OWC+qmz04H3JhjhK3pj+KbKogIq71rwQhSpNzsz3g57+AIHS9rq8cOnVAYb3VTvC/eDh97IFiPHngAYHLn00RqBTNw==,iv:97EqMIDOOCuWxb9a2jKnAyMnnFjScQNZvfrmxFzf5fw=,tag:+mjXXKXbIVnIKpKXnj80Pg==,type:str]
    username: ENC[AES256_GCM,data:Z64P0moKnHBJo0d4,iv:bqO2VVqG/FrcQWMofY0Hr/Kh44TCRGAgg2ySfdR4cOc=,tag:/7TI/lSdr15ssMiHpIr13g==,type:str]
kind: Secret
metadata:
    name: grampsweb-db
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEl0aHNvVG9pa08yTlFu
            ZEdqU1V2ajBhUFdIaHRMVWJrYU1IbFJ2alZjCjIzMFVvSTFqeTV2L21JMVkwUHZT
            OThKemJjdmR2OWczQVBMdmdwMWpxbUkKLS0tIG5vT3k3MXlQcFczZHdjMEdFNXBs
            ZDZwdmxFdFhOV3BjR1RncnkzMVdOQVUKElo0EOw0RYD22hM7b58FAO1+ZGAvOeS4
            EFp1w6H7bmhvhpdLWGC5ORpplCDFOFqvo2KvEaq/EIRs9foDNN7KJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T20:52:59Z"
    mac: ENC[AES256_GCM,data:Eez2sx36x02gxsZx75k2hm696pMKIEt2kpg1Gi2HT9LxiyXA+EHBkrFkcnriP5zh3PgMptf09/wstvn0CbXGVONtycRz61oaN/QZz6P05ontCw/I9zC34yuDe29iqDEVeEe6NBM052joy91+WrmltehdhCOB+5XS2zgiTFrGu2k=,iv:spyV++l1+OX5KYWM7DZY2LTozPYOws0dBMcNFZ9C9T0=,tag:nJp2U7GTP5zEOz6UE77LWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    config.cfg: ENC[AES256_GCM,data:nEyl/LMjYSs1IkqnvGdZULCSdpIv5CmuM9RqZNbqCAcA0lNDxM8F+Atw2/eSxipYlkvjMhNz1ob7JIAFGwOzQY5/ypEn+x0byU/GQ9eUD6rGbtZY8yzxN1hLJSklbwTaWWGQ0AtFYaA3H7D9zjHm3JlCdSBhXItiBswIbJnZlSvCPB7GlRtBBTTPdRe54JEo9DL0zsanQ3VXYoH4yrOYc8tcE5ZOPpHKZfA8CPDlQ6s2B6fDAiX3RFe15MlBr+HpzXcNl5gnloS43q0IsVVfiKmseniV4E2e5MYZ4zPqdpg2x7ANW7xv4pqnOMTRrGuEicf7mXrb8aLHMO10j3eny3GULVIXATcAzN6fkfpWuzd2s8BOzEX6REeXa8mTFAL8afRBfFtKYTFxhKlf8TNBTyw5QxB+zGVmL6LyMxv9F/ZI1KLPu9V5P91qGz02EF2bWGxbmmHBBQ0zfjmlkbwSk9CZOJOszlfDgF+AVw1zSnXsOloAK6H7UhKX3mLr9oUWTFZ6GoXBGatmtuIS2OpicLk7AIxyuGRjERwNfonZtp9pcggdzsseDp3J4QPSGQkCpIEb54moGpwRVOWPAkmkT0SeCe4JYbLPJLCvhhgIyGb+mhCUJsRDA2C2EB476rAxunYgGXoiNhnjdngOGSGaX6gvUW54veywCdU4rZw1QieKEb+zRB+kaH//CEAB1HFEjM1yh0DuVX+dh5qbLMyoSAIoT23sxX8RaA7vl9bLVQgkx5HpWrcRYvTmsb94IsmlBy4J1OQhsVliGI1aJ4KcmFDE+IOpJ7g28cvwO58bxkZFwI8s3+FZpU6r7Oijmc66U84pSf361R2oLI62DOHMK/D410PkJSEt1PsMPbBsy+626bRxY8qjdTMxBzz5tGvAzQx63fwWqNkYcuuxmcBHXncTFUcsY3INl5GziHUMsumwIE9hXBGf0Ztbhhh0lS65VAor6/bjUhu4bSShtAowgn3AunT519AYkSkDl/qSbNL6iomJfsSWQSIbfdS1HIZO9sMRzcBCyaMgtuz5DSR+93/9W7zHjUexWdVo6X6QMVOQFANxh69oeySJv5+Br5DfdycvUtX4D9XCjeQsO+6A1FsFK36SJ3llf2U5RL9RcNeK+TSfjTYW3CTvJ7hKXtBAyTEzYzLDv0tx4IJzja/cRI1lewjnWVdeMX5G0tziwwzkpqfMJ2caEMVR49lO1tsa6Wat9t++Z8dyeG3eN5N20M+5egX78NMiErbGlTkFeaqbZnzYMDeUpyK0HYBFgyn6GfEebDtEB/Cndtfqny7ZJ9tw3ziKyNwK9nJxzZnyu8BCOppvmhTNqtLTTZf3yABy3WrcfQrA15inKhKe1dF7T50mcssI2eemZ0Q1/amp3BSdnjX+KEAV+x4gI9Oss8/dM7ggknwe+hHSQTgwVv4/lz+laL+RxsZ2V7a/mqArdQR64DLWLeb+CNaZrQIr2YUTnzLG8MBgstCvEFB5,iv:zeVuwC647aUWBDP5tnU2yqGoDjLkQc9qDwgMJxF3FHo=,tag:6rEaXPBenzUlAu7x0do1/Q==,type:str]
kind: Secret
metadata:
    name: grampsweb-config
    namespace: grampsweb
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTnNNb2dGdFlLZWowbCtw
            RzNlR2ZJQzBoeGZwaVdLQUtKL3RtNFA1c2tNCkl4VE1VRmlpUzliOE1QWm1oeEl0
            ZExwenZPL2pHMnFSRkJnOTBwbWRNQmsKLS0tIFFmZ21ObE9KMEltWTNvQTMzMzRY
            SHAvOGEwd2lrdktQK09zRTNSRitmM0kKIhhz/3K8GWpnm/JT/epYiR6SLSaA1CRB
            MEMT2sEhG7y4OAfXotmOblG63zNUTqnoAirubu21U2ENrg2RE7K5hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T21:28:43Z"
    mac: ENC[AES256_GCM,data:Cr+43CeTXqJuo/P9/tj/L/0IuXT6i6gcQVLCE8m4j4Fppcb+Ssy1tp+RWmPYGcb+qzfJ0ArtR5Mwg+nPNoMK13WFyrU0i87sWwrXkYuBqaH7eMjgGrvKAqWPKGwTLObEijQrcKi4OiHITyFkaXzA7a4HP/kEdmuEqtBIn2MN/IA=,iv:X1YIhtzxjpHiKJ1BXwau9GAIYWfMHZdQw6pIYlArNrA=,tag:cOPEaDaG9snYNDxk3WSnsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
