apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix
  namespace: kiwix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwix
  template:
    metadata:
      labels:
        app: kiwix
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 100
        runAsGroup: 101
      containers:
        - name: kiwix
          image: ghcr.io/kiwix/kiwix-serve:3.8.2
          args:
            - '*.zim'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: media-zim
              mountPath: /data
      volumes:
        - name: media-zim
          nfs:
            server: 10.0.150.100
            path: /mnt/DataVault/Media/ZIM
            readOnly: true
