---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwix-media-zim-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - soft
    - timeo=600
    - retrans=2
  nfs:
    server: 10.0.150.100
    path: /mnt/DataVault/Media/ZIM
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: kiwix-media-zim-pvc
    namespace: kiwix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-media-zim-pvc
  namespace: kiwix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: kiwix-media-zim-pv
  storageClassName: ""
