apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-staging
spec:
  acme:
    email: acme.fpdj9@simplelogin.com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              namespace: cert-manager
              key: api-token
