---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.raymondcollazo.com
  issuerRef:
    name: clusterissuer-staging
    kind: ClusterIssuer
    group: cert-manager.io
