apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:3hSBcy7nTSgSD9mChumTZrVdFGJz03BxvLOPkYhli1t24Dep7wRvtjpEl+qnfAW2dgz02e2YtPo=,iv:ae0Ceg3kVvF/j8gZAziU9OT/5p7dBhGfUVDEkocJues=,tag:SaUaQ3UJ8wA6cEKHDyXu7w==,type:str]
    client-secret: ENC[AES256_GCM,data:FevrJ4+m65nYbOVhyyR/hjaJO86aF6nvhE6GlR8KrklIyEpIIgymXaWm3yK9uVPkxjeu9pGPfpcVEkoZCduZoR07N079LNi2Em1LgJqxV3JbNS8mGrYsyaBIehf5sAr1UAmrUEGR5NCbFzJ1/q+wb4qeIVImETTf1jhJP9+hIb9dTPGTZowMHtkLnLZ/L3sipds89RRBhYXMpuQmxrW/UO4AoOcF/JfdNoHpeQ==,iv:CZMlYNNPho2cKMze0v7uOLQlRrspALAE1uCTM5MmNXY=,tag:kOnUloP+PHVoossaS6WLqg==,type:str]
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeUg2NjBwYm5NeE1zak5H
            WFR3TzJRSnZ5VDBEV2s4aDhFN0NwemkvWFJZClIzeitRZlNrMGRxS0c2VFRSa3ZD
            TElaUmNwWWZoV2g0cmg2cTJqWm5LZW8KLS0tIDU3NVlWbnIzSjdyODFqL3dyQ2JX
            UE8vSGErWXBES1ZUSlV4WTFkczA5bHcKC0qYj7PDtVJSC8nGI6ndRouNPDHsuE7A
            qUSRm0BEXqpCITNgJGzI8SpsCE6KYnAj6aIVx3VVOhy2q2ibUeoJDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T00:45:05Z"
    mac: ENC[AES256_GCM,data:QAIPXPOORYB51mP83P7TAFDV5g1JgWsOyUaSFjFmOiFkPn8FbR+nWWmIYFmTiYDjs6XEWtnGKaHizl9waQ+z4LZLHKmavQZuCBO1FpgaUlpqCvW6ty9ioaxKmofuyBeX1uQbfHLT5miXYHY0K3o5skAYbBo1P0+QnlZRndNburw=,iv:urOaZr7pggNCjwn1UQZpdzyIk93Dnenayrg/f79D9dI=,tag:bjdhUxYxKMHmbac2QGJCfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
