apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:Ryn7OJDt6vx6DvqpcdSTgfKMY5Kif4+Vrw/XHXzrsirAK+QFqnKuzhuEtVNWhE7FRvhGqyzfKhM=,iv:E7zZyIaojq3F1GfVCKwsGMz4zIGnNKhbO0cZBmxm3gM=,tag:Sdh+lPXDHL5bHNc5ah4eEg==,type:str]
    client-secret: ENC[AES256_GCM,data:tmIxxxnUUjMWHOLZGYPiflidsAEtG2RBJQmnXygj3MI1pfTtxpjcWyotkSazEaigM67BXWzXdrxAtJed82cNnlrgbq7Y9KzlcPXl4y/QNycn+45nU6ltHJQMA3vXFsM7tzREX/586EddzQHq5ODo341Js0lkKr2mPpl9F5NBWCj3e7PfDWlM2Ici2EfOnCZWDy6AvgVp5MvgA/F7GCDvNLTz0gX2jDaL02YbUQ==,iv:g6P1m0jaN0/wMbu5I2NHOCHKXGGu+J94vjYfPIEBUA0=,tag:gN/285xbCJJ0Q9yd6Oeixg==,type:str]
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb3VsbXJqZXJ3SmpEbXZW
            WENEdC95Q2c0UlBSYlYrMW5FVmF1Y21XMTBVCjB4NGJGWE9hNXg4c3BXekptQUVn
            WTFJeFF3SXY0YXZQWnhadFN4L3lnNzQKLS0tIEJFUDBxaGdicnhONHZTZGtOaEJz
            MlRUdTNnQkJRajdmRVIwQWZkMWdsNHMKDFUU04n+A5bUL2ZI1fgktYoO6bQwSkSS
            popCkcc9Ejk+PrPI+mwD8y2eGH7hGsfg2iV5jZ5jooXqtT8GJ7sdCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:27:07Z"
    mac: ENC[AES256_GCM,data:/N83y7kCGMwhZZJ9ebbLr4K5SvdJh+sGSikcaUyPA/hcS6723ReYEApiMHGGkTv0Is5wf+iBQQbziCEBwyUSqpa/Xn8wXWQk241ngNCnlgrkoB5/HUZmw3V1166/goMRbEBIoO8MXwFVv9JjEbV9LiW68pH0ZVwRS3pgB1xMorU=,iv:zUeYZsBIVxuwtdN0lusIbIlh8vTh4QCYkbs0+kY8z+o=,tag:ksp5htzd6C8nTR2z7QTtBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    mattermost-webhook-url: ENC[AES256_GCM,data:W+TpSOXsKVJp3YTRtPaFaaGtc2N5xV6y1HmlcSoxx+VxeQzTaLq/DkOwB+FgZUh/7nsUzwVkblLptAjUQ9tlKKvqq6Kxb/qdTXYiU+lBSYPkrFgUQzd+TQaN5bN8y2Rb,iv:k27VrrgvUH7DAaHeCK/K+yHtRumFKiU8xNN7lwWwn5k=,tag:5E1SK/Yj8vffLp9isH3l3g==,type:str]
kind: Secret
metadata:
    name: grafana-alerting
    namespace: monitoring
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGFkWDlVMXN2akxPVUh1
            U0RxRzVGZXY3UkpBcVpLeWVsREJoYmVzTng4Ci9ZZ3pNR2ZkUVh4ZHcrUm9veGJu
            a2p6WDRNa2hHdTVSOWQ2L055b09TdVkKLS0tIDE1WDY3M2RUME5YUUdqZzVEL3dw
            UjdFeWpvVHJMcldGcFJRZGlxamVucUkKs0Qx+cpT+WbQLQ6EMYCpTYPiS180BYDu
            mQCtu+P8DTAy92LhT2BkvJh9Nq56/2OT4H1SbUWwUnYFVTaRIQwuNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:58:51Z"
    mac: ENC[AES256_GCM,data:sHjDhExDRAsnzzbmngXseUUAFS2wTkro71nb+awWiisCytxdd9bcbaQreZEkipvRyiz0SFbocXajhxN+9JhkcMkt246QiY0wxRXwo4G7VU9/7SoU/QCxe4z95Mhzp6Esu80wT0OBtNoCOS8S/YIQZ1owO2bgFAd88zYUTB/TjvE=,iv:h67jgydsASMkXqEEtH+siTiz3dbh3P3KdQwIxK/SEqo=,tag:P20CTs0CKuGRBfg6jAAQ+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
