grafana:
  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
      secretKeyRef:
        name: grafana-oidc
        key: client-id
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oidc
        key: client-secret
    MATTERMOST_WEBHOOK_URL:
      secretKeyRef:
        name: grafana-alerting
        key: mattermost-webhook-url
  alerting:
    contactpoints.yaml:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: Mattermost
          receivers:
            - uid: mattermost-receiver
              type: slack
              settings:
                url: $MATTERMOST_WEBHOOK_URL
                username: Grafana
                icon_emoji: ":bell:"
              disableResolveMessage: false
    notification-policy.yaml:
      apiVersion: 1
      policies:
        - orgId: 1
          receiver: Mattermost
          group_by: ['grafana_folder', 'alertname']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
  grafana.ini:
    server:
      root_url: https://grafana.raymondcollazo.com
    auth:
      signout_redirect_url: "https://auth.raymondcollazo.com/application/o/grafana/end-session/"
      oauth_auto_login: true
    auth.generic_oauth:
      enabled: true
      name: Authentik
      allow_sign_up: true
      scopes: openid profile email
      auth_url: https://auth.raymondcollazo.com/application/o/authorize/
      token_url: https://auth.raymondcollazo.com/application/o/token/
      api_url: https://auth.raymondcollazo.com/application/o/userinfo/
      role_attribute_path: "contains(groups, 'grafana Admins') && 'Admin' || contains(groups, 'grafana Editors') && 'Editor' || 'Viewer'"
