apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: mattermost.raymondcollazo.com
        service: http://mattermost.mattermost.svc.cluster.local:8065
      - service: http_status:404
