apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-values
  namespace: cloudflared
data:
  values.yaml: |
    tunnelConfig:
      name: kube-homelab-staging
      protocol: http2
    tunnelSecrets:
      existingPemFileSecret:
        name: cloudflared-credentials
        key: cert.pem
      existingConfigJsonFileSecret:
        name: cloudflared-credentials
        key: credentials.json
    replica:
      allNodes: false
      count: 2
    ingress:
      - hostname: forgejo.raymondcollazo.com
        service: http://forgejo-http.forgejo.svc.cluster.local:3000
      - hostname: netbox.raymondcollazo.com
        service: http://netbox.netbox.svc.cluster.local:80
      - hostname: grampsweb.raymondcollazo.com
        service: http://grampsweb.grampsweb.svc.cluster.local:5000
      - hostname: mattermost.raymondcollazo.com
        service: http://mattermost-team-edition.mattermost.svc.cluster.local:8065
      - hostname: auth.raymondcollazo.com
        service: http://authentik-server.authentik.svc.cluster.local
      - hostname: linkwarden.raymondcollazo.com
        service: http://linkwarden.linkwarden.svc.cluster.local:3000
      - hostname: freshrss.raymondcollazo.com
        service: http://freshrss.freshrss.svc.cluster.local
      - hostname: kavita.raymondcollazo.com
        service: http://kavita.kavita.svc.cluster.local:5000
      - hostname: rustfs-s3.raymondcollazo.com
        service: http://rustfs-svc.rustfs.svc.cluster.local:9000
      - service: http_status:404
