operatorNamespace: rook-ceph
monitoring:
  enabled: true
  createPrometheusRules: true
cephClusterSpec:
  resources:
    mon:
      requests:
        memory: "512Mi"
    osd:
      requests:
        memory: "2Gi"
