apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: "1.18.2"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 12h
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  values:
    configOverride:
      configOverride: |
        [global]
        osd_pool_default_size = 1
        osd_pool_default_min_size = 1
    operatorNamespace: rook-ceph
    monitoring:
      enabled: true
    cephClusterSpec:
      mon:
        count: 1
      mgr:
        count: 1
        allowMultiplePerNode: true
      skipUpgradeChecks: true
