apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rook-ceph/
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: rook-ceph-values
    files:
      - values.yaml=values.yaml
  - name: rook-ceph-cluster-values
    files:
      - values.yaml=cluster-values.yaml
