---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-database
  namespace: nextcloud
spec:
  instances: 3
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: nextcloud-db-store
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nextcloud-db-store
  namespace: nextcloud
spec:
  configuration:
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    destinationPath: s3://nextcloud-db/
    s3Credentials:
      accessKeyId:
        name: rustfs-backup-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-backup-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 30d
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-db-backup
  namespace: nextcloud
spec:
  schedule: "0 4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: nextcloud-database
