---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.150.100
    path: /mnt/DataVault/NextCloud
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nextcloud-data-pvc
    namespace: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: nextcloud-data-pv
  storageClassName: ""
