nextcloud:
  host: nextcloud.raymondcollazo.com
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    usernameKey: adminUser
    passwordKey: adminPassword
  trustedDomains:
    - nextcloud.raymondcollazo.com
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array(
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.raymondcollazo.com',
        'trusted_proxies' => array('10.244.0.0/16'),
      );
  extraEnv:
    - name: REDIS_HOST
      value: nextcloud-ds
    - name: REDIS_HOST_PORT
      value: "6379"

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-database-app
    hostKey: host
    usernameKey: user
    passwordKey: password
    databaseKey: dbname

redis:
  enabled: false

persistence:
  enabled: true
  storageClass: ceph-block
  accessMode: ReadWriteOnce
  size: 5Gi
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data-pvc
    accessMode: ReadWriteMany

ingress:
  enabled: false
