apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: signal-cli-rest-api-data
  namespace: signal-cli-rest-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
