apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - ../../base/open-webui/
  - ./database.yaml
  - ./datastore.yaml
  - ./route.yaml
  - ./secrets.yaml
  - ./scheduled-backup.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: open-webui-values
    files:
      - values.yaml=values.yaml
