apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9easkZoeCbr5mkL58b03osforViTO0P2ZVi13+RbYXxL2qYE05Ot6IaJpuA8gvACV3u7IkIprTjme3h6sGnvIBlvekslH5BAGB2zIFb3fAfA4ASolfBC3Q==,iv:0z7kkgGorzgIBSaVri9wrts1NMgJ9HcPTQaiL134vi4=,tag:SXrJEzOfS8KT6QUChorUTw==,type:str]
    username: ENC[AES256_GCM,data:h/sVVSS5GmkPyUysS6JpzA==,iv:y4Lvpr0NZAlUc7yfp3u2HRdQ2AR+zWseU0Z2BmimdP0=,tag:eM2ZblK2gj6T6I2UrmzIdQ==,type:str]
kind: Secret
metadata:
    name: open-webui-db
    namespace: open-webui
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYVp4c2o1aU10QnFRcGkw
            YmJMaWlCd21iQVVwaCtHUlB3djRIZ3c4dG4wCjlOS1F0Q3d1MUMxNG8zSFBkSzZ0
            Tm1zZjNUeUVkOU1qSnRCRks0UUQ5NkEKLS0tIDlFaHhxY2UrbWd3QnNneVVtRDdN
            VVhubUg1Tm9pVnhQYnpJK1NzQUdjNW8KL+2kLnIGWxMQfG25A8xNNpCSSuJYadhQ
            aJKPQZQ+ZKD0J0wSmipzmqW9ZD5LBWeMe7D+xBcEFsIFQASGrXipHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:37:28Z"
    mac: ENC[AES256_GCM,data:tar5iXv9TFCFNuCtpXAkOS6aA8BKF077Zwg1LCAmeYJHET7jmm8m1I1euWUJaZuzpaP255VRseI1V3dgd36gVmB8yjV18g3SDVD8TxY3c0ZTgpXIYyNe8KxomcQGiTb9OclOZXyKT3B3NPN02kDeBai8Z5eJGsPKp5T8Y/w3u7M=,iv:EA5v3bkPvNinKkN5FnA7pWQoepoSMPdimX0TFinCZzA=,tag:sfPtO2BVUdGsO7LAzZ8Pvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:nv4bV11NEZRRLQvhG376xzVdOCrQanFZ2HfNGRrkPlb9YlIZrBqZfv16YKNDEdxhAH22yXG+xY4=,iv:0yN3KLcjwgWFBZwbN8LMvW/id71OLntyT0/HqRV5NPQ=,tag:Sipix0yuWOr/tvGJzIEYIw==,type:str]
    client-secret: ENC[AES256_GCM,data:6wsZe6/GtVqTzXZ+/JoeRwJ2f8CWR6L4L1XquTgNTJJE8AQTosa+RikPjQC5yWDvmkGGX5e2AF6OPaTPiUYGa1ASFQLhQJD7sZenzlL4mreBi538GFWN11DFfSB9aVAGEsO8CzxM7I1UEh6YjfKOv0vgCZ3mV4FaTyvFEPcAtKkgQdWL+TR0PX1apk79Pj9MG4z0YxD8+hNDudZ3YZWWzg/NBRqFEjG6p1qOFg==,iv:7exfksdRF+AB0SzQwHFwpPIyLZKMJRjGpmy5OnBqYdU=,tag:IJf99+OLx+5UWYerq+/HQg==,type:str]
    webui-secret-key: ENC[AES256_GCM,data:UG682U+M+c9uEJTralfkweP4iukgq2qxiq23F3Ly5iSh2DJaGyKf6qnViFkKPnUxPPVJARPLBGWjFXRS2MxYSBPgp9qJsWlMrKRtMDNIbwxMFpzH45L/Yg==,iv:3dABjuyix+KU7DcfEd6uZEQDCuEEUPFB/k9k3EF0Rbc=,tag:0dBcpiNiYmbtQRVVK7VHmw==,type:str]
kind: Secret
metadata:
    name: open-webui-oidc
    namespace: open-webui
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z05oVEtWeHl1SSt3VUMy
            eHVrTEQ2WkczV1Q4cGd2dlY3aHAxUG5tUzJvCnZyV21LMDBJOWNCUGViUndja25v
            Y1BOYUgxSWlDYUYwL3I2T3ZVNnl3emcKLS0tIDc2djljeSswWlZzM2RoMTlNMFor
            eEdacG9NWW9HUlpGdElQYy9meDhzcVEK2AGgCcIPoOniy1D5ubN6paEZ35MDuTsi
            TtuO0xDWV1dPUx3uoFAJ7JZ53G4x2nyrBHkIObFX/r0G3yfbe8Iprg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T19:53:25Z"
    mac: ENC[AES256_GCM,data:XnfrzhBoslF2BhrV/lut6rhixJOap6QIwlW6fYh00r+/8F3psoXSFmG4Ctg0/EwGAl1Dt1bf6huejnJ1Hglhwi2BgT+BagqdBukgALR0enVMDZpFiOWI46+SvkGvBMcqrpXSpYSa+bua0e1XtCrgqH/MY/rfaliMI5HoCzDUB80=,iv:S9YQtvw6k+dGEPdsUtgm4fG3CrNFRxvfqIPuZBrDFIM=,tag:xya7scemKAJxRvDxnl3eGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
