apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9easkZoeCbr5mkL58b03osforViTO0P2ZVi13+RbYXxL2qYE05Ot6IaJpuA8gvACV3u7IkIprTjme3h6sGnvIBlvekslH5BAGB2zIFb3fAfA4ASolfBC3Q==,iv:0z7kkgGorzgIBSaVri9wrts1NMgJ9HcPTQaiL134vi4=,tag:SXrJEzOfS8KT6QUChorUTw==,type:str]
    username: ENC[AES256_GCM,data:h/sVVSS5GmkPyUysS6JpzA==,iv:y4Lvpr0NZAlUc7yfp3u2HRdQ2AR+zWseU0Z2BmimdP0=,tag:eM2ZblK2gj6T6I2UrmzIdQ==,type:str]
kind: Secret
metadata:
    name: open-webui-db
    namespace: open-webui
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYVp4c2o1aU10QnFRcGkw
            YmJMaWlCd21iQVVwaCtHUlB3djRIZ3c4dG4wCjlOS1F0Q3d1MUMxNG8zSFBkSzZ0
            Tm1zZjNUeUVkOU1qSnRCRks0UUQ5NkEKLS0tIDlFaHhxY2UrbWd3QnNneVVtRDdN
            VVhubUg1Tm9pVnhQYnpJK1NzQUdjNW8KL+2kLnIGWxMQfG25A8xNNpCSSuJYadhQ
            aJKPQZQ+ZKD0J0wSmipzmqW9ZD5LBWeMe7D+xBcEFsIFQASGrXipHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:37:28Z"
    mac: ENC[AES256_GCM,data:tar5iXv9TFCFNuCtpXAkOS6aA8BKF077Zwg1LCAmeYJHET7jmm8m1I1euWUJaZuzpaP255VRseI1V3dgd36gVmB8yjV18g3SDVD8TxY3c0ZTgpXIYyNe8KxomcQGiTb9OclOZXyKT3B3NPN02kDeBai8Z5eJGsPKp5T8Y/w3u7M=,iv:EA5v3bkPvNinKkN5FnA7pWQoepoSMPdimX0TFinCZzA=,tag:sfPtO2BVUdGsO7LAzZ8Pvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
