apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9easkZoeCbr5mkL58b03osforViTO0P2ZVi13+RbYXxL2qYE05Ot6IaJpuA8gvACV3u7IkIprTjme3h6sGnvIBlvekslH5BAGB2zIFb3fAfA4ASolfBC3Q==,iv:0z7kkgGorzgIBSaVri9wrts1NMgJ9HcPTQaiL134vi4=,tag:SXrJEzOfS8KT6QUChorUTw==,type:str]
    username: ENC[AES256_GCM,data:h/sVVSS5GmkPyUysS6JpzA==,iv:y4Lvpr0NZAlUc7yfp3u2HRdQ2AR+zWseU0Z2BmimdP0=,tag:eM2ZblK2gj6T6I2UrmzIdQ==,type:str]
kind: Secret
metadata:
    name: open-webui-db
    namespace: open-webui
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYVp4c2o1aU10QnFRcGkw
            YmJMaWlCd21iQVVwaCtHUlB3djRIZ3c4dG4wCjlOS1F0Q3d1MUMxNG8zSFBkSzZ0
            Tm1zZjNUeUVkOU1qSnRCRks0UUQ5NkEKLS0tIDlFaHhxY2UrbWd3QnNneVVtRDdN
            VVhubUg1Tm9pVnhQYnpJK1NzQUdjNW8KL+2kLnIGWxMQfG25A8xNNpCSSuJYadhQ
            aJKPQZQ+ZKD0J0wSmipzmqW9ZD5LBWeMe7D+xBcEFsIFQASGrXipHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T06:37:28Z"
    mac: ENC[AES256_GCM,data:tar5iXv9TFCFNuCtpXAkOS6aA8BKF077Zwg1LCAmeYJHET7jmm8m1I1euWUJaZuzpaP255VRseI1V3dgd36gVmB8yjV18g3SDVD8TxY3c0ZTgpXIYyNe8KxomcQGiTb9OclOZXyKT3B3NPN02kDeBai8Z5eJGsPKp5T8Y/w3u7M=,iv:EA5v3bkPvNinKkN5FnA7pWQoepoSMPdimX0TFinCZzA=,tag:sfPtO2BVUdGsO7LAzZ8Pvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:rCOzIkwwNsvES9TvZad35rkEyoahWBN54LZQ76I2JJdnJ7TMk2VYPwt6pVRZ0wfc1VI42hyo9oA=,iv:123sqmQoCJZHnOf0Iv+t2xF73VU7Lm262H+Rk1d4/7Q=,tag:q/9FV5rA8ND/Bv9c/A05UQ==,type:str]
    client-secret: ENC[AES256_GCM,data:aMLdrZG22Pwib80C8VYktOHWIpAKKXSea9UcU68h9B3cOTAgAuvJVFhir0mzZT+mji119hamWyY+NytCPJZZ4w6U5DgwqXxXmNkIdphUfYAIQN1QOeX5qWWOVjuUjS6hFcbQSr/2xBC6Xj+zdXUe7+H+BYJubsKEzfvWXhZt0TFdIbizST0Ub8AGw/sRPahfAujiBDmMvLXKhSgIezbsVOGz0ubhdWhOuJ0BOQ==,iv:5TnxqhvndiJtzVKVxqhEknim3UxiADJdimyKBwTkqXE=,tag:O0fizZaRaisqh9NDq0iFUg==,type:str]
kind: Secret
metadata:
    name: open-webui-oidc
    namespace: open-webui
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTUJRT0duMlRmRVBhcmdX
            Q1JVVkoraGpvR1BRbWw2dmtDbGhOUDhydlFRCnJEcURSR3l5YUppQXBaQXhBaFFl
            YzIxZUI1d0lXUFM2OGZIWTluOERkTG8KLS0tIDQxVnpPNWFuRHJXNzlmcHNac3dS
            VVNXRTllY1c4bzdnR1FnT3NIakt3RmMKlX8cQ8id2ohCb7dAO9qqfJul1s66hO32
            8e/P4s1+z5TrC53uuE7PyRvnzK17JOoQ3vJ3ekiUXtvXGi7l9tmpfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T19:33:34Z"
    mac: ENC[AES256_GCM,data:yJ9Q7iOxYkyQlmFlNkq5UFZyIphO7Gtm/KUF9z0pervBUYR6y22viOSkUn7V2cknKPRGcOnsvF13/1Nj8QtXlt9KqDZvgcgeriQhqTAkrwp9z4cTWO9MNhnU3KuVTOjMJrPdEVHQlDI1yxE2QKLyCnBcFwR/64T+JuoIL2CPpUQ=,iv:LCq5u1+XC3Sojmd0Osk1iCHAmMBgaQN7H3ESrKNK7Ac=,tag:uo+LB9/RgyVOAkMruRvBBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1

