---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mattermost-db
  namespace: mattermost
spec:
  instances: 3
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: mattermost
      owner: mattermost
      secret:
        name: mattermost-db
