apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ejphDfeCzFf+A4BpqGHzczR+Alc4SX1g7orSsDENgq3kJTBgabCfU/qxXzZPCWu0WpXCU/IBblPic6/+kA9yJnXOGPVkMNzjmJwojVZZpRgnLSh/YmWu/g==,iv:8FHy9o9GoCdtaTGuwBFGsBry2jSTxEEg2iGq/2tTx1Q=,tag:Rz4vKK0KhCy9FMO8XNAmSA==,type:str]
    username: ENC[AES256_GCM,data:rPq/SqqyVQ13ORfQfY3fxw==,iv:kExXMEFr1hCaLDg0o8DuI077ecw5z7dHZ4XioGSnaiM=,tag:hVH4yxIi3SyTD3fV24te8Q==,type:str]
kind: Secret
metadata:
    name: mattermost-db
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzJsL2sxMGFMaFQ3Mk5i
            TVU2SHhMWVZHeUVxKy9EbHlGcmZrdGhEa2tnCk4xOXp0NGM1NEp5SHhBcUozTFgy
            dEdhbGoxTFlvY3ZScnp6UzM5QkpTaWMKLS0tIHBURG0vWjZHUEJmdEpOcHNSWFBa
            eUpnRDRTUEhpVWw1V1F5bmlOQnJFMzgKZpE8q4GqEyoXhWxAbgSFPZMkzicl3o1+
            9CEKbY11RfRPwnDTWb/48IYKs8/D1IGouKOpxXVzYP1diMEYPXyE+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:57:30Z"
    mac: ENC[AES256_GCM,data:ZspzdcnEBpoYazAKjfwrQhzoJ4IpY5YpXv+vqUSA1rqMJ1ulp9bWybdiNgY3B/MfO12iIf2A59En9EsBAyBipYDbXtdBuGkSDJeG2wYrnc6Cho1FRVIlBCVYIQPrSDp+hOvG77lOJ9i5BerT/N5TiQH4AlmJcXD4ezEGtvkzGY0=,iv:ffvEH8+41J8BKAb7bKVPYhaDv4IPhNjX27TCX7nTuak=,tag:EAP9+VAcxGRIRpa2VwVxxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:DevBHmPpEcW1MfhYtg7lsvYHxG8J78yU4w8LKiYwSbZj2DfBReBoO0gb1x1bnJJ/9d1H8b+qEnnnVRrLL2AWhapicqGFl0EtK/vrbRwdwVAL2hMUoBbV4kAlGrtQgAi0f3IDHCz88iqlMp2PwQAtfO7l//5/J3E61E8QL3Y2M6pPYlK9F+X99RqZALcoA7XNPA7F7+XyIlISDIiZOrjSBGwyJDX8oY1QhfVQowPUux7+o5UrPpaQSBGOBV4CShkQem6kO1O7Op3+ZVQnB7Um1RDUnbampnT/1Szx1yynbTqNP8bUTRkTblPHUgssV+aFs55FrQ==,iv:uyEYKw8G7/H+LgBMatbxgUjRj9ZyA3pgxlAHREsTxas=,tag:6uaQ+NtWYRGJiwbczvGYYA==,type:str]
kind: Secret
metadata:
    name: mattermost-db-values
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzJsL2sxMGFMaFQ3Mk5i
            TVU2SHhMWVZHeUVxKy9EbHlGcmZrdGhEa2tnCk4xOXp0NGM1NEp5SHhBcUozTFgy
            dEdhbGoxTFlvY3ZScnp6UzM5QkpTaWMKLS0tIHBURG0vWjZHUEJmdEpOcHNSWFBa
            eUpnRDRTUEhpVWw1V1F5bmlOQnJFMzgKZpE8q4GqEyoXhWxAbgSFPZMkzicl3o1+
            9CEKbY11RfRPwnDTWb/48IYKs8/D1IGouKOpxXVzYP1diMEYPXyE+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:57:30Z"
    mac: ENC[AES256_GCM,data:ZspzdcnEBpoYazAKjfwrQhzoJ4IpY5YpXv+vqUSA1rqMJ1ulp9bWybdiNgY3B/MfO12iIf2A59En9EsBAyBipYDbXtdBuGkSDJeG2wYrnc6Cho1FRVIlBCVYIQPrSDp+hOvG77lOJ9i5BerT/N5TiQH4AlmJcXD4ezEGtvkzGY0=,iv:ffvEH8+41J8BKAb7bKVPYhaDv4IPhNjX27TCX7nTuak=,tag:EAP9+VAcxGRIRpa2VwVxxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TrXdbI5ws/Ik+CtNcHrfS2/duM6jFIHmlzSmwRfT9ssoCC0Vf6Bcqi9O2Y7T/Hl9E4igFlI7BR2Hc0o/agy3lXD02Q7+5xxUHCX7+Y2Kpd84rTej5B8MqQ==,iv:5Zln9bN/yVXf2hrUCeEf0AnyLmavPbjZRouafq04DAI=,tag:Yaj/7NgneOZrBEH2oAl9vA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:72Wwt6H7l8xWt96JHhdgGVGtBR9HKan2kLxS6M2vk9aDICJFm+00vchouRjsGiJSLrsAnRz2uJzF10SX02QlpAHjOAdCFnlnbYK4NxxftL0aEwp/lHuGIg==,iv:WkNfBoH5+nDtXkpX6WgiAtAmx35n9HLNRhQhaflmYyA=,tag:fArRWu2EekWpfZODJGI4Rg==,type:str]
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cHppeTUvUG5rVFVnZmVi
            VmQ1ZTdwdVZOL1FNTHJobXB4MXpZRUZxUXd3ClRUTXFSVzFETWFBNXU4RDM1Z09V
            emxnRXZvbmttMGd4VzZpRmQweEdJV2sKLS0tIEFPa2NCTWJiNHIrVTM0cnBrV1Va
            NFVhVk1DS2RGeVY3cEx6UzdTSk1QUXMKdyrMcNacrnU0OZUgzDyHQZRNpA382hY3
            +2aAJFOJrHmYSgNCGAlMfSlEqPRMI7MrR/wlXSXwp93wH0j5PsW20w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T01:59:40Z"
    mac: ENC[AES256_GCM,data:rnLU/F9CgXib0+ChCMukN3ZW7p/5z6qSq1i4UBhmhXq1OODlGQIA7yk49JZeag7PJjRSX3L8V2YIHL498uSZPJSJdHS3zcdF6yIIH3YpiquoLT5s5pI87aIRgiesv6CTstGG5nkG7M7VCblj7iWorBoRChFc2Sx+vYyJLCUtXlU=,iv:geY0vvxJGqBeS+wi5XIJuSCMT63mdFWL2ax3VgAuEfc=,tag:fovYvxL3itfN+m0BgJwgBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
