apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4+jkgbGvLunNRZNm0q58SZErp7z5UvGkLLoDr+YBPjJHtg5g6RCIK1KkkAe8E/ZzPxLJDBROcloJYZJlm3tpBRQed2u58JX4R4fN6/4b1anl3KUNTWzQmA==,iv:dDpJi9f4+xtV/n7iltVUm4zSto64cJj8+vtdTmoD+8c=,tag:6rRERwSHsQQSNRdIBvOiIw==,type:str]
    username: ENC[AES256_GCM,data:AEq5nvxekr9qm82oAIOEjQ==,iv:2QhUya8iVyZFtPDG6lcT0xnwmnqvISYgxcW6sJkIetg=,tag:vybfZeaYaM0oBOsqT20iMg==,type:str]
kind: Secret
metadata:
    name: mattermost-db
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaEwrOVA0M2NJT3hSdWs0
            NFdDRVBOR0pXSU4zU0xyd3RLTXZ4NGtzRnlJCmtzaCtPQU1DOWp2QTY0YVRVNWNp
            L3A0MlAyZjR3bFdUeHZGRDhkRkJmMzgKLS0tIDIvbUI3WHphaUNOVVREeVpZajEz
            K2pMZXhBN09HUUVZWFVSVjYrR0lHNDAK1UvDTX9XfhS3UC5iAWDyz03qIzC5Dql6
            +nYEKRrkGlmZM7fuJe9Q1fXyRWmkrAkcQDZKwnARqPNDSY9LhtnUjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:42:23Z"
    mac: ENC[AES256_GCM,data:fA/6pawxCYHEnRRFGMZvZlAVIUqAHmkKlsHOlnAfcdc5hdpu6zUXO24MlNX383URnwFG/RdT0IF+wD+XspUlEkbUiTqEaQf1mVn8bDFcqgXlQ79Itl62XhOy/edts38tV/44CysiZSd8gwyie6rzC1cHyGz6atiQWEb2VOAsXFg=,iv:nHJ8ieKt2kPqMGwm7Kv1f3d+pbNIOoCHaQp0wzihzOY=,tag:G8hCacSStNdTJT6RWeDlFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:p8bqAweB37u9LUHlGGAuA02Ayyhf7LZV8/3XbvDQvj1w7oWHL4Ug2+vJmQTJ56ONjduJ0+aCc4T7jqCmpbUydzkiL4rqu2zY3uTF23dxRgDS7Otkccly6cnfLgwG075b4LLBjD/mEVSe3WeGRvCxyVWNXs/px8g7CiPAcyAu9+iGvD12ZRbx74WuWRvQ3mSGGJPgBfzCBbAJ1kv/BftkQQi4vQOonhQ9hIlEF+6cWi+e3BrAZ5o9biTmnPreVcETFUoXU+8geLDyNzVpBPSLbC8vY6m8PtEVXXJ9iewHcrDjkbOSbZ3WveVjPVEGF1e2C+EnYBmK7wdAaVQIhW+DdQ==,iv:1HL4HRNSF1HrfOdEnaUSzDMfvW6nT5fDMO2cN9COfbM=,tag:oFWQNpAddvCyKwbFWXn2Gw==,type:str]
kind: Secret
metadata:
    name: mattermost-db-values
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaEwrOVA0M2NJT3hSdWs0
            NFdDRVBOR0pXSU4zU0xyd3RLTXZ4NGtzRnlJCmtzaCtPQU1DOWp2QTY0YVRVNWNp
            L3A0MlAyZjR3bFdUeHZGRDhkRkJmMzgKLS0tIDIvbUI3WHphaUNOVVREeVpZajEz
            K2pMZXhBN09HUUVZWFVSVjYrR0lHNDAK1UvDTX9XfhS3UC5iAWDyz03qIzC5Dql6
            +nYEKRrkGlmZM7fuJe9Q1fXyRWmkrAkcQDZKwnARqPNDSY9LhtnUjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:42:23Z"
    mac: ENC[AES256_GCM,data:fA/6pawxCYHEnRRFGMZvZlAVIUqAHmkKlsHOlnAfcdc5hdpu6zUXO24MlNX383URnwFG/RdT0IF+wD+XspUlEkbUiTqEaQf1mVn8bDFcqgXlQ79Itl62XhOy/edts38tV/44CysiZSd8gwyie6rzC1cHyGz6atiQWEb2VOAsXFg=,iv:nHJ8ieKt2kPqMGwm7Kv1f3d+pbNIOoCHaQp0wzihzOY=,tag:G8hCacSStNdTJT6RWeDlFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
