apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ejphDfeCzFf+A4BpqGHzczR+Alc4SX1g7orSsDENgq3kJTBgabCfU/qxXzZPCWu0WpXCU/IBblPic6/+kA9yJnXOGPVkMNzjmJwojVZZpRgnLSh/YmWu/g==,iv:8FHy9o9GoCdtaTGuwBFGsBry2jSTxEEg2iGq/2tTx1Q=,tag:Rz4vKK0KhCy9FMO8XNAmSA==,type:str]
    username: ENC[AES256_GCM,data:rPq/SqqyVQ13ORfQfY3fxw==,iv:kExXMEFr1hCaLDg0o8DuI077ecw5z7dHZ4XioGSnaiM=,tag:hVH4yxIi3SyTD3fV24te8Q==,type:str]
kind: Secret
metadata:
    name: mattermost-db
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzJsL2sxMGFMaFQ3Mk5i
            TVU2SHhMWVZHeUVxKy9EbHlGcmZrdGhEa2tnCk4xOXp0NGM1NEp5SHhBcUozTFgy
            dEdhbGoxTFlvY3ZScnp6UzM5QkpTaWMKLS0tIHBURG0vWjZHUEJmdEpOcHNSWFBa
            eUpnRDRTUEhpVWw1V1F5bmlOQnJFMzgKZpE8q4GqEyoXhWxAbgSFPZMkzicl3o1+
            9CEKbY11RfRPwnDTWb/48IYKs8/D1IGouKOpxXVzYP1diMEYPXyE+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:57:30Z"
    mac: ENC[AES256_GCM,data:ZspzdcnEBpoYazAKjfwrQhzoJ4IpY5YpXv+vqUSA1rqMJ1ulp9bWybdiNgY3B/MfO12iIf2A59En9EsBAyBipYDbXtdBuGkSDJeG2wYrnc6Cho1FRVIlBCVYIQPrSDp+hOvG77lOJ9i5BerT/N5TiQH4AlmJcXD4ezEGtvkzGY0=,iv:ffvEH8+41J8BKAb7bKVPYhaDv4IPhNjX27TCX7nTuak=,tag:EAP9+VAcxGRIRpa2VwVxxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:DevBHmPpEcW1MfhYtg7lsvYHxG8J78yU4w8LKiYwSbZj2DfBReBoO0gb1x1bnJJ/9d1H8b+qEnnnVRrLL2AWhapicqGFl0EtK/vrbRwdwVAL2hMUoBbV4kAlGrtQgAi0f3IDHCz88iqlMp2PwQAtfO7l//5/J3E61E8QL3Y2M6pPYlK9F+X99RqZALcoA7XNPA7F7+XyIlISDIiZOrjSBGwyJDX8oY1QhfVQowPUux7+o5UrPpaQSBGOBV4CShkQem6kO1O7Op3+ZVQnB7Um1RDUnbampnT/1Szx1yynbTqNP8bUTRkTblPHUgssV+aFs55FrQ==,iv:uyEYKw8G7/H+LgBMatbxgUjRj9ZyA3pgxlAHREsTxas=,tag:6uaQ+NtWYRGJiwbczvGYYA==,type:str]
kind: Secret
metadata:
    name: mattermost-db-values
    namespace: mattermost
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzJsL2sxMGFMaFQ3Mk5i
            TVU2SHhMWVZHeUVxKy9EbHlGcmZrdGhEa2tnCk4xOXp0NGM1NEp5SHhBcUozTFgy
            dEdhbGoxTFlvY3ZScnp6UzM5QkpTaWMKLS0tIHBURG0vWjZHUEJmdEpOcHNSWFBa
            eUpnRDRTUEhpVWw1V1F5bmlOQnJFMzgKZpE8q4GqEyoXhWxAbgSFPZMkzicl3o1+
            9CEKbY11RfRPwnDTWb/48IYKs8/D1IGouKOpxXVzYP1diMEYPXyE+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T22:57:30Z"
    mac: ENC[AES256_GCM,data:ZspzdcnEBpoYazAKjfwrQhzoJ4IpY5YpXv+vqUSA1rqMJ1ulp9bWybdiNgY3B/MfO12iIf2A59En9EsBAyBipYDbXtdBuGkSDJeG2wYrnc6Cho1FRVIlBCVYIQPrSDp+hOvG77lOJ9i5BerT/N5TiQH4AlmJcXD4ezEGtvkzGY0=,iv:ffvEH8+41J8BKAb7bKVPYhaDv4IPhNjX27TCX7nTuak=,tag:EAP9+VAcxGRIRpa2VwVxxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
