apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2025.8.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  valuesFrom:
    - kind: ConfigMap
      name: authentik-configmap
    - kind: Secret
      name: authentik-env
