---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: mariadb
spec:
  interval: 24h
  url: https://mariadb-operator.github.io/mariadb-operator
