mode:
  standalone:
    enabled: true
    existingClaim:
      dataClaim: rustfs-data
      logsClaim: rustfs-logs
  distributed:
    enabled: false

secret:
  existingSecret: rustfs-credentials

config:
  rustfs:
    log_level: "warn"
    log_rotation:
      keep_files: 24
