---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actualbudget-cert
  namespace: actualbudget
spec:
  secretName: actualbudget-tls
  dnsNames:
    - actual.raymondcollazo.com
  issuerRef:
    name: clusterissuer-staging
    kind: ClusterIssuer
    group: cert-manager.io
