apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets-store-csi
resources:
  - ../../base/secrets-store-csi/
configurations:
  - ./kustomizeconfig.yaml

configMapGenerator:
  - name: oci-secrets-provider-values
    files:
      - ./values.yaml
