apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical
resources:
  - ../../base/infisical/
  - ./database.yaml
  - ./backup.yaml
  - ./datastore.yaml
  - ./secrets.yaml
  - ./route.yaml
configurations:
  - ./kustomizeconfig.yaml

configMapGenerator:
  - name: infisical-values
    files:
      - ./values.yaml
