apiVersion: v1
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: infisical
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zGanBoptke9bN+BJJiTkvTdPidqSMO4UdfU5qM9SgavExfUaacODm4UF96D6sEzeI4wzINs0RTdYfK2w37VeeqBjMFDvfcqLlUt7D3MxIRezLAAb0NQ+ew==,iv:i2VuYICxwiCoDe8Rn4paT5N2vbgo9GVkXAB+Ao71CA0=,tag:xpL+HEW+Sju4y/oVPV7TSg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:EF9enHRsK3BZaLVgktBFhY9GzmjC/hyRfn/A/2YPrsU0SkRYNOg1TaB6bi+16uzc7JV5GBTksF41IMNxoSAtS8VVwikll+5VnaieO3zB06EQX3AwYba62w==,iv:NbHVIoXIUcaN795zHnBml2n2p/HjUqlHkQF8exVFQvs=,tag:ZFNncMEZqSxLlQ70V3HkTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT3ZuV2YrNkg4K3hmNkhr
            ckY3QU95MmFPQ0M0SDNLcVVOajBLbkROd1hnClZXV1U5TE1jWExXTWpWTjUweHEz
            cjdndkJMVmgrVXVDK3loSUJCVStZT2sKLS0tIFp0SkNmbEd0RnRBMFliTXg1bUw1
            UW1FQnJkdU1KOXNFYVN0bjdidzErUG8KPIDck71mMg//89IBbABA4th2i8OnQ3IL
            ETsLTc6ET0lTKW0wZf7tyXRVunKTgb1TbaEZnnl80jJ81aG0s+hx0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:36:23Z"
    mac: ENC[AES256_GCM,data:61MW82bo0HO6EQksMDrufX9EzXPeSAgiJnLwGPk7+d6ULNegpXme/BFgkig+ZeBiAotOQwNHrxHM1CBfJw7K1Vel4lyuXXjU6lRJGPM7uQL3zJ/IJu4M/V0pyX5OQTmlru3ZOg9f4UrRLZjq88WhwtEu2JT7/nra5EuRhXufga8=,iv:3PcZJwOyufKsqfri6YKOA5MSJyj+BWnFHd06Hv/4e1U=,tag:THXopLicWb+D7mX3ogWmSA==,type:str]
    version: 3.13.3
