apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: infisical-oci
  namespace: infisical
spec:
  provider: oci
  parameters:
    vaultId: REPLACE_WITH_OCI_VAULT_OCID
    authType: user
    authSecretName: oci-config
    secrets: |
      - name: infisical-auth-secret
        fileName: AUTH_SECRET
      - name: infisical-encryption-key
        fileName: ENCRYPTION_KEY
  secretObjects:
    - secretName: infisical-secrets
      type: Opaque
      data:
        - objectName: AUTH_SECRET
          key: AUTH_SECRET
        - objectName: ENCRYPTION_KEY
          key: ENCRYPTION_KEY
