apiVersion: v1
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:NYAmb69k+5LGs8W8l4vHMa1o/PHVNjBNgYV0GDto9H2iOWUNgMBsuLVYFILS6oG83ZSCTJFiMwUXPFxJNS+EXb+RVZjxzDo0904e+qMJFDPkpxvmpp48ig==,iv:dgjWo0tK0Cj7NR/hdx/ZpZ97SudqzbaN7fnEuic83gU=,tag:51fLHGIs3FRYjvyR98YB/A==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:WB+DhAsrgQ8k3t/gSQ8pYeQtM2gZ/bjitLZ+Be7qprUNM/cRnRenNtqKfEmeytpYhStsxZrvE/YxbT11GrkBAZBjlJX6H7EIqyzKHRvzhYwHayOcjBu7JQ==,iv:esFpNohcFGxVQ6Iw0B7hJKYqpZUUfdAfcNfnUQqz+KI=,tag:yDkoC/d2Fc2Dwt9FsUhXfQ==,type:str]
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: rustfs
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEFYR1JtZU5scUlmekIw
            dWJqR0VkcHRMS2ZCb1U1ejRhNU0xOEFYTW5FCk9DRUl1L21PRGYzd3I3YXFFQW1B
            ZHRLSm1QaE1EQUNaVWtsUGlaUlF4MDQKLS0tIFZSTkZ2VVJGRy9SQ3Fhc3JxYnhs
            UGIrU1VaVjNxaS83WG1jYzlVZEdrRGsKjmk7pbQDGTBJSnxY07mkCWjiYNobVz19
            83gi37sjo0B29J0BBBgEgF5gm1IMwbEUt080Z5Mhy5LcNafh1yJGNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T22:09:14Z"
    mac: ENC[AES256_GCM,data:nb23x3zGf8aDYZH3PlPf6XTGwGjDn0gPdkmB8ixV3jorLmGRw3VqmG5klFEFFt9fQ+kIYuFT4DE17sOADzRdF+MgLiZ0Bka6tCf0PkctAQdSOwP5N88meWuaaheRuxzFppIaIJd7jcg1OMidoQ1nX/G0j+RoNbMgCNfVuZaRskA=,iv:Py54We9JWSTBY4SN9VtLg3Av+yFPr1Vt+3+j3kPgP+E=,tag:ANeyoGx3lwFfRfxDyufTDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
