apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oci-secrets-provider
  namespace: secrets-store-csi
spec:
  interval: 1h
  url: https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts
