apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-operator
  namespace: percona-system
spec:
  # releaseName: pxc-operator
  interval: 15m
  chart:
    spec:
      chart: pxc-operator
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: percona-system
  upgrade:
    crds: CreateReplace
