apiVersion: v1
data:
    key: ENC[AES256_GCM,data:2ekmmzw6yIDk0hQhK+Isbx8UwXiRv1GTXxEIFuBDosCwv8gCy03PJj54FSK1XHPu8ZCWtgTPEBs=,iv:Mpjtbh7i3EfepnIZnt5pPAoaMl6zWK8QFA1VYymkK6U=,tag:BNCAXZGfm3tI7otvjevJIw==,type:str]
    secret: ENC[AES256_GCM,data:9lUtyBu7kA0Oo1Aael1lZppgCNZlfn9PWKwYRGDIN5tg4OaLy1U8VkWpdBhTgPJ/7IkNY6+5BHV8o/gNTclJCOo7DFmxayCebA0DHZOm7o2hfiwk2ZpcMtPnp7xCmPtzhMewofe4+jzi64CPiNk16T3ZLhe8S3IR5NOGvW56l9r1bMz8J4FODrIq0TuML2LT0f3yz2G76NZaqwx/maRqgC6Z632SZGfcZP+uPg==,iv:TYntM69m/MYuPdqEwQ/v/ujChgMgkajcxpSLpRUggRA=,tag:Q+MvwfMagTYQNE+RD7gi6g==,type:str]
kind: Secret
metadata:
    name: forgejo-oidc
    namespace: forgejo
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNVo5QmpqU3JxQVZJZjI0
            UTc1b21TdzlvY0dlYnduSUlRNGpMMkdhdWdRCklacGwzYUQ3TUUySW5sbEZSaGVR
            TjQrRG5YeWJIdjNEUTdxcUx6c2JwM3cKLS0tIHJPVXJFalJ0KzNEVUdMRHhtaDRH
            NXFQTEU1QjlYVXdKNnNIcGhkWG40UEEKaNXCtdTCHxIaP51ft1wKQAP5s3ppbQeJ
            cyV66Gr4OTXmnqSIgOCuAU7F6W/9ke3U7Ld+TMiXK53aJMrPAm1Wnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T05:19:54Z"
    mac: ENC[AES256_GCM,data:TlkST+f0luoD2PUz9E1bqd8tl6/c3urtl4kHVs6QinnVPxJnQlpT49GSKEJikTjvpJTSkpJ5OdfiDTzOjW8wMIciEF9jmXJ3uXhPR3zhvG8Mrrsxv7CEjUuQpQvYGs7cIMOmXNu4PSUP8JSNtCBa6VLKuuAe3sfIQ0xxYAIwG+Q=,iv:vf/0EISzxtE5dNXnq/5YMZ2CnbOMmlrMlGZTN6OZGRg=,tag:L5PTSevP99/PlJ6VKTl6aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
