apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configurations:
  - kustomizeconfig.yaml
resources:
  - ../../base/smartctl-exporter/
configMapGenerator:
  - name: smartctl-exporter-values
    files:
      - values.yaml=values.yaml
