apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:rE8/82ZMXjbbBnZJph2Neu/6LJx6/OLJjpBonSWUZq9gq///0U+Hu7Do9RMzvJ7KDnbOr5P/hXU=,iv:7WOtkzFYuWxM1sVXjYjY0K3bRCmvImBhxKtYWJNBkWI=,tag:2kf3BAQxcN0z2Rt6CW6GrA==,type:str]
    client-secret: ENC[AES256_GCM,data:mQ2kDQQvZrAChBKqnJBUzPE/qVNaIvux1bJIga8HOMmf2VyGY2Sk3rn+Ecf3orXQ+462EiG8OOrAukFap6iivlw2BX8E6JpOxr4VJf7ZjT4Bbzptk0eUUjH2oBiL4fL4ShRNo9u33qg4sExLDRBjxR+ASBqCByBShzpweXVxraDsZZTYn7trCeI+EQfR5Tq2s8oPyFrS9Iys4JS0GMX13WahJrXAUE4A/hzwRA==,iv:bpRq1LO70TLTc0UCjlmz6i8upxcvKvroTXyfN45jNPk=,tag:2XquhuK5+EHO2Tq1YMXauA==,type:str]
kind: Secret
metadata:
    name: jellyfin-oidc
    namespace: jellyfin
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV1F3WjFwdGtTMzluVk5h
            UWp2cWtHVkFnTzZidnkyckI3bTN1VmxuZHkwCmc5eTQrODVWY1BDRWM0cEI2WFZL
            dmJ3dnFZWmlkNXpMTVE2U0RIei82N2sKLS0tIEpRYktpVjh1M2xJTDV3eFpEMCtn
            N0Nsblg1NExYWVhBOXlmTEdwOU5QOEEKTJS1ZS8sGyrvL/m1VaeInRDkjtywRbO7
            b39wvV0LVtoOywubcY7/bb0bG2PZR0GfwWrpvFUS2eCCBv/g7FEqKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T18:04:03Z"
    mac: ENC[AES256_GCM,data:gvRtJJ0M3fgSRb0pyO/yNif2eCOJgO8d+SbTANDbLoJPKbbRCJlcoP78kgAH1wQHY4hu8JHri6GNnV6S4eDK5GheDuTJI4P1d/35Ga+HmU/d5KSzm3rHCLoKzBQmZoX7IvVA080MxCs4nhjq98eyU3kbzHBXJafX6NfM2GRbzvY=,iv:8OKKRGdAVA6ZXj6Pf2seL4K/CdMoC6L9RfXaCWfPvPc=,tag:9bbXr3mRM9RIEW9GBSGXqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
