---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zap2xml-epg
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 500Mi
