apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./serviceaccount.yaml
  - ./secret.yaml
  - ./clusterrole.yaml
  - ./service.yaml
  - ./deployment.yaml
