apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actualbudget/
  - ./freshrss/
  - ./homepage/
  - ./kavita/
  - ./kiwix/
  - ./linkwarden/
  - ./mattermost/
  - ./netbox/
  - ./forgejo/
  - ./n8n/
  - ./grampsweb/
  - ./immich/
  - ./open-webui/
  - ./nextcloud/
