apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: "./config/crd/standard"   # or "./config/crd/experimental"
  prune: true
  wait: true
  force: true
