apiVersion: v1
data:
    NB_API_KEY: ENC[AES256_GCM,data:e2/p3EcJudcBw1FLDzrAnQyaZulVKz3NbQynykLyICFwlkxX5EqqGfcN0hrTsKxLjm3QHKJxouI=,iv:3yGECr4HNBfk+6oXpHgh+iJvxK4j5gq64rAOV+N2yXs=,tag:AfnPJiKjywKKdOHFiuvevA==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d0ZCSnNJaWp3QmovWll1
            OE0vYVQ3VXg5Qmd1RmZwWHF5RnNjNFYxZ3dNCjFnU0JTSHREQklkV3ZkUnQ5RmZa
            RTQ5TmFSOG5lQXo1MVVEUEpMaG5wVXcKLS0tIGNWT29ObUh2a1htRis4VWY5Qjdr
            M1dpRGZoMWcvbE9UaVRZQUtJeGRkR28KS1vJOj8i5d9+UaQoM2NjIjqMcZ9VCST/
            P7zSijo2OlPGcG5idskonmb7aoE06jCDgtmFLlHha22VMebNVxGK2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T04:20:00Z"
    mac: ENC[AES256_GCM,data:g6mX579bhesvOroisPiNai1ZZFyqhVhycKJy66wIgyV07TPwHDY8LGjrRY0RrtlKphYqPKoA30AwAsWIZLCtiS2Ys2E9VRhgeEf+SyzLdmJdC+cqydJzQAOnol25EDdVIfVV4dKvohiJdmvotehJZA3Jk0JLy3UNBVoEJPIQw1U=,iv:OWo/RElwzCaBljWudrECtfl9lFVeacAofkYWlR84nhw=,tag:oODiO8NJoea6tKocQGq+nQ==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.1
