apiVersion: v1
data:
    NB_API_KEY: ENC[AES256_GCM,data:7aTSjtDKK6+D8bReL4zLizuWu5HmHZMpkw8KUwOGib8zT4fRN6ZdM4nHIKU5En9Sz7a9TvpuC6M=,iv:soulEPuoeVWAfoqwJpV8MZBe5AUovG04IvBKS37KKDw=,tag:sLGVnrWE/yUquO4kj5xu1A==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEJLd2R1amNuRnlXU2pV
            OHRVaHo1aUxpYTlPekFlSzQxRjczdkM2QkFZCmxpcGV3NFF6bkxROFFRekhiNW81
            elZOamZzc1N2V3hoNjJHU2duRGFYWTQKLS0tIEJJOW1YUytlMFhIZFdZemk4RzNS
            U3dTcFN4eDNZM1lBR0RwYk01YXRWMTAKuSX1ga4+R2fM3pdy8qteAdfsz79Si/Ni
            qPR0AZ7uVX8cvfLisi40eXCO6/2aJrCiQE3xo2r8rBRd123YoPaf8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T04:14:39Z"
    mac: ENC[AES256_GCM,data:zSkP5bULVrcHyLSdq1xzSKcSAtYVNe7cB9/9tJ06aFM3GNRlkc2pCOrr12ui4Z2js2E6cimczVDt78RCtpzgA4mIgUsWGXuMlUUOxe3CDMlYHhlgW1DNvLIainALt66bjzhJ02EJF3SSJVXTAFk1B0HDcp402Ss/3hFDOwehzTA=,iv:Bh6feVpeX4NboCT/9ob3dznlNpH+vUUYTtq5VJzchio=,tag:6XsvkSAIahIOZoIKCNsAog==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.1
