apiVersion: v1
data:
    NB_API_KEY: ENC[AES256_GCM,data:309YdkzUtfGIlM+aaKKF2KNnMs2tvBqnxGQSrCiQvJTKcgB8e6MB5BmRHnRVAqrkuUx/vBIHD0M=,iv:97Ygoho8kJT/syNPMAKoKly5TT+7/Bab2fxuFwDk/Uc=,tag:2rTHVOKEr2GPndnVNEGmrg==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMk9EV2hxZmNpbDZXV2pZ
            djdMRzFYUzBsWGNYZXJTbjFINDFwUmVpNlY0CitKOW9kdHlja3ZlV0JyY2s0Z0Zi
            QnBSQ2g5M2UxcXYxQ3hJOG94WnlwMU0KLS0tIGErd1YyV0tOVVRVekpSOWVmaWVV
            VCtpK3diUlo3TTZsSXozRnhKeGUvQ0UKculB09OhX1+19kSz98Rq2qztMbWsfJI6
            ZzGvPZygNoo1bz4LWesFy0KDrFBwOmUvaHpehExoXSNhAM5hJms0Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T03:56:33Z"
    mac: ENC[AES256_GCM,data:QCkonHAvIUM3Xahkqwbzj4mtsGgvss0oNr1B0TPoA/UsgDp7GOyVCFJuqK+rkRDdVmnXWhfElGQA5dwpdsNO+h7P5TygFDLVL0P6bQ0LqNSu10OwZMbYG4uGWq5vEUeyRisBd5etSH6dsQd5+q7hiPRi6lPVO/c5IB3yeR2jDB8=,iv:Rx8VRlDrnKRKbYd1+27/gtemVjLjb+V7sfiAVNgH/fc=,tag:HVoSQBfGtfuIRvJAlACU2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
