apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  releaseName: 
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  upgrade:
    crds: CreateReplace
