---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: unifi
spec:
  secretName: unifi-tls
  issuerRef:
    name: clusterissuer-racknerd
    kind: ClusterIssuer
  dnsNames:
    - "unifi-test.collazoirizarry.xyz"
