apiVersion: v1
data:
    password: ENC[AES256_GCM,data:xAkXndr6umuetj1HaNMyuQ6bir+h9GvTcz0S0FCWd5A789tJSfW2xUmpZU8=,iv:+p1KGLx+nfr4EB5bw2NAIzWv53Ke50PEA4kQXna2l3o=,tag:W06aNz6rsHiLOvCjKSz6Ww==,type:str]
kind: Secret
metadata:
    name: unifi-db-password
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1dZaGVzalZwaHdkZnZu
            WE0vTWU0SWhaU3dQMFFYaE50QzlNbUJwY0YwCld0NmZlMklDNVMrNnFQK2Q4Mnp4
            OVUxekNlQWZPc1ZyTmFBR1VOYWJDWFEKLS0tIHp2OXdVMmcvYTJrS1lUa3grY2Nh
            aTB0ZFpMQU1ubVlDTW9lUXV6T0xvRFEKSQPPiLf3779K9fTtyhu3XMozOg/SKf1M
            qJU/OqergywM27hUBmdY1q9+PW+2DH/29bVwYJis8hKe0/qfUfsEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:46:38Z"
    mac: ENC[AES256_GCM,data:dy96mQUexGdu1aKjpwl00nKqb89oyYJc0+7hH3FCJZl2V6fy0Bz8NLlyJ84d1PlcfRRkPxdvplF0IRoocm4kw53y2j3j1jnEyt4ql9dzHU00j1YI7i/FW/yF2Bab+OarIb58JN10e5RoafEmG9WGAt+8/E7NchvJPnETqVvNbM8=,iv:/mwkXnBIlb/Se1TQsy3gfO7p0vQP7yR6JCwBWWyHyGI=,tag:J6poySm7zy5ngMbLo39Baw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    MONGO_PASS: ENC[AES256_GCM,data:9lVlxckl+sCqGOp1aNmv7gjxRjgREGLaW4992xroS3f0iNCOYqmRr/aXwbo=,iv:N+kCSP3i7nnbY38z1rIBL/vedKeu8tek/qyjCRsTRDk=,tag:Nnu1tlkrvHcM8tLN5WFVyg==,type:str]
kind: Secret
metadata:
    name: unifi-secret
    namespace: unifi
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1dZaGVzalZwaHdkZnZu
            WE0vTWU0SWhaU3dQMFFYaE50QzlNbUJwY0YwCld0NmZlMklDNVMrNnFQK2Q4Mnp4
            OVUxekNlQWZPc1ZyTmFBR1VOYWJDWFEKLS0tIHp2OXdVMmcvYTJrS1lUa3grY2Nh
            aTB0ZFpMQU1ubVlDTW9lUXV6T0xvRFEKSQPPiLf3779K9fTtyhu3XMozOg/SKf1M
            qJU/OqergywM27hUBmdY1q9+PW+2DH/29bVwYJis8hKe0/qfUfsEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:46:38Z"
    mac: ENC[AES256_GCM,data:dy96mQUexGdu1aKjpwl00nKqb89oyYJc0+7hH3FCJZl2V6fy0Bz8NLlyJ84d1PlcfRRkPxdvplF0IRoocm4kw53y2j3j1jnEyt4ql9dzHU00j1YI7i/FW/yF2Bab+OarIb58JN10e5RoafEmG9WGAt+8/E7NchvJPnETqVvNbM8=,iv:/mwkXnBIlb/Se1TQsy3gfO7p0vQP7yR6JCwBWWyHyGI=,tag:J6poySm7zy5ngMbLo39Baw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
