apiVersion: v1
data:
    password: ENC[AES256_GCM,data:xAkXndr6umuetj1HaNMyuQ6bir+h9GvTcz0S0FCWd5A789tJSfW2xUmpZU8=,iv:+p1KGLx+nfr4EB5bw2NAIzWv53Ke50PEA4kQXna2l3o=,tag:W06aNz6rsHiLOvCjKSz6Ww==,type:str]
kind: Secret
metadata:
    name: unifi-db-password
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1dZaGVzalZwaHdkZnZu
            WE0vTWU0SWhaU3dQMFFYaE50QzlNbUJwY0YwCld0NmZlMklDNVMrNnFQK2Q4Mnp4
            OVUxekNlQWZPc1ZyTmFBR1VOYWJDWFEKLS0tIHp2OXdVMmcvYTJrS1lUa3grY2Nh
            aTB0ZFpMQU1ubVlDTW9lUXV6T0xvRFEKSQPPiLf3779K9fTtyhu3XMozOg/SKf1M
            qJU/OqergywM27hUBmdY1q9+PW+2DH/29bVwYJis8hKe0/qfUfsEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:46:38Z"
    mac: ENC[AES256_GCM,data:dy96mQUexGdu1aKjpwl00nKqb89oyYJc0+7hH3FCJZl2V6fy0Bz8NLlyJ84d1PlcfRRkPxdvplF0IRoocm4kw53y2j3j1jnEyt4ql9dzHU00j1YI7i/FW/yF2Bab+OarIb58JN10e5RoafEmG9WGAt+8/E7NchvJPnETqVvNbM8=,iv:/mwkXnBIlb/Se1TQsy3gfO7p0vQP7yR6JCwBWWyHyGI=,tag:J6poySm7zy5ngMbLo39Baw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    MONGO_PASS: ENC[AES256_GCM,data:9lVlxckl+sCqGOp1aNmv7gjxRjgREGLaW4992xroS3f0iNCOYqmRr/aXwbo=,iv:N+kCSP3i7nnbY38z1rIBL/vedKeu8tek/qyjCRsTRDk=,tag:Nnu1tlkrvHcM8tLN5WFVyg==,type:str]
kind: Secret
metadata:
    name: unifi-secret
    namespace: unifi
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1dZaGVzalZwaHdkZnZu
            WE0vTWU0SWhaU3dQMFFYaE50QzlNbUJwY0YwCld0NmZlMklDNVMrNnFQK2Q4Mnp4
            OVUxekNlQWZPc1ZyTmFBR1VOYWJDWFEKLS0tIHp2OXdVMmcvYTJrS1lUa3grY2Nh
            aTB0ZFpMQU1ubVlDTW9lUXV6T0xvRFEKSQPPiLf3779K9fTtyhu3XMozOg/SKf1M
            qJU/OqergywM27hUBmdY1q9+PW+2DH/29bVwYJis8hKe0/qfUfsEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:46:38Z"
    mac: ENC[AES256_GCM,data:dy96mQUexGdu1aKjpwl00nKqb89oyYJc0+7hH3FCJZl2V6fy0Bz8NLlyJ84d1PlcfRRkPxdvplF0IRoocm4kw53y2j3j1jnEyt4ql9dzHU00j1YI7i/FW/yF2Bab+OarIb58JN10e5RoafEmG9WGAt+8/E7NchvJPnETqVvNbM8=,iv:/mwkXnBIlb/Se1TQsy3gfO7p0vQP7yR6JCwBWWyHyGI=,tag:J6poySm7zy5ngMbLo39Baw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ClTrb2odqEUJA4bEBcKpfCol9fR4rKcUJ90l3amCKWtwDvNWaR5EhkoE+9VnVlcSkt1uohfMU3nC6cQ1WZ5yPxy5Sy0HvQICHSZtpL/mOqf/wVZKzHrmcw==,iv:vSSnk/AsLIGXh/8A6h0Q6X/jNVnGT2vvPG8FAPAkFfc=,tag:W5qbCZIG8AcS0rdOFMYU9w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Xi3svGlCT1BAn4plfIfBqaf0fWT0hZdkZ8ZDU54VeUbUkBQM3RxZbNaF5sFNvyIZX3Fwg/xNv+0978Psamk9yT4TZyfUjefI3BrPV/bTZUS10WLrMiPmlQ==,iv:dmFi2Laa9/6Q98RkkIbOMCGIjvavDBSuO8k1SrNBiz0=,tag:5nrmrYBotGvOU4uSebZQ3w==,type:str]
kind: Secret
metadata:
    name: rustfs-backup-creds
    namespace: mongodb
sops:
    age:
        - recipient: age1gxhgy64rr6u6rfw9kkawq40j4k3vfnha53rc7rxwnp4hjzm64ymqfu57gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTnUvWVZwZUdzb21vQ0xy
            N0xXUkxyNDErVGhBekZvZGZuVjlLYThKWUMwCkd4cGpLL3BVWXpEM3Z3YTFoY3hF
            OXQrMkVxVzhCZi8wNlJaTHBzeXh5OVUKLS0tIGNJWVdKcTZBRm5yaS9OR1NvMERT
            QzFQL2luaVFlREJxRGNwLzd2b2dpTUUK6FTmrvhXzemkmFGfSNIH9WAEsL67Bde0
            dAUeOvX1zO5eciY5vMZJ4nVS8gQ2QXtAPzCVxAa+s4NA6chyi9X3DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T06:41:41Z"
    mac: ENC[AES256_GCM,data:GTB5uc0O5qj5pMo65UfsVzU8cV1Nfk3WAnsTQiM3tzss5mXjaBQYsPH/92L6bpd28N/CmYOIzuxn8HHCgv9o/RGrOinCIZ5U1olZP5Fu/DZh0k1Q6yCUTM8N+uxJxwGYZNTOHwCJiebNwynh1abQXr8sxjWvQD8n9uCokmHsdBQ=,iv:2oGWcEyU02fA9zdElSHszEGC0RSEP3PhDqnOo+/9Cm4=,tag:iuJoI80SJUjrckzmhnDshA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
