apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  interval: 15m
  chart:
    spec:
      chart: actualbudget
      version: 1.8.4
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: actualbudget
  #valuesFrom:
  #  - kind: ConfigMap
  #    name: actualbudget-values
  #    valuesKey: values.yaml
