apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkwarden
  name: linkwarden
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - image: ghcr.io/linkwarden/linkwarden:v2.13.5
          imagePullPolicy: IfNotPresent
          name: linkwarden
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: linkwarden-data
              mountPath: /data/data
          envFrom:
            - configMapRef:
                name: linkwarden-env
            - secretRef:
                name: linkwarden-env-secret
      volumes:
        - name: linkwarden-data
          persistentVolumeClaim:
            claimName: linkwarden-data
