---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: paperless-ds
  namespace: paperless-ngx
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
      add:
        - SETUID
        - SETGID
