---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway-crds
  namespace: agentgateway-system
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway-crds
  ref:
    tag: v1.4.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway
  namespace: agentgateway-system
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway
  ref:
    tag: v2.2.1
