apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: devbox
  namespace: devbox
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: devbox-root
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          storageClassName: ceph-block
          resources:
            requests:
              storage: 20Gi
        source:
          http:
            url: https://cloud-images.ubuntu.com/releases/26.04/release/ubuntu-26.04-server-cloudimg-amd64.img
  template:
    metadata:
      labels:
        kubevirt.io/vm: devbox
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: devbox-root
        - name: cloudinit
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              hostname: devbox
              users:
                - name: ramon
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  groups: [sudo]
                  shell: /bin/bash
                  ssh_authorized_keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINaOkYtQfBDiugCaHJ12rDMpJq4Zq96QIeCO/b4rnw81 ramon@bazzite
              package_update: true
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent
