apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hubble-ui
  namespace: monitoring
spec:
  # releaseName: hubble-ui
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: hubble-ui-values
      valuesKey: values.yaml
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
