apiVersion: v1
data:
    cert.pem: ENC[AES256_GCM,data:eb2ZOSY+FhK1lZ5qxZDRjtMXJfwb/dRMznhZeO560qX++aDNEr+7U8E2OoeX7jVP8WAXzzLTQWoXHuZtsxhMLIgoPwS/nlzrecCpfpIsZVNiTDEm8qxIugNiEG1zaD7Cn5fdvMBP+8LqzoXPfhEVHmxVXe6uBi8lG5XoROHjXgG9Y62IevQ4Noy+Ays6xb0ht+aXEO5ZuNd4pKWZKkuQOiH0nGrQfG8LPKbQNkuBNt2nFnzheNTgXmUXjlRWeaWK0wejcSnn/iS4JVs3nGE6Z/J+o1TCno8jfTb4LUwIXzenYb/57RawAcB2gZkyeX7Coh/LKsLerPQ7aMcM5ovktCvsg7T4hjbSb7N1OVdLCBjKsz03rwHRmR3GLG6DsOny4yEXp9KSjYxraTVAlr0KLZX2xsJChq7Si5AlTUbIfKsHGDEM8pLN9p/a7L9ph3P8WGeImMOnwm3nRTz+d/YQ0ZY7A3s=,iv:AgoqgzuDjnNHnJ+LBXn4py+8Zisir2Ofh01h4PiSubw=,tag:84jpEj3d2Tj3KjS74SbvKQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:i4uLf226rhDrcYcejTiMYzx6H4+T/X8utBSWN6GqS2Q8M70EPQobIRD8KNBMyaNmSG7koYWj+ddTmtwKIv8Ppj9/Chm4tXjubu6GG8hfVVZ9900xLVpkIOl8P3vkiKhdaim2NZ9D5ocxPS2UAEF/OR3kwmqT6vz3g29aAaCZHDqZOSGqzwbLB3eoyTLyHTdeBjwiMX7cKNsveGK4XIYQxFYVoSwdUFj8QUquy/46RE0QvtwvF+wuMWpBKedXC1furXxv2kdmuTN9k52rBLSDHBTVFME7MDkZ6h6RSBcsydnLdC3Fym00Bh3g1e4=,iv:bAP3oKP9Pw08A+A0xaDFHASc1/zAEVa20COvEgu/ugE=,tag:LWnXaWZf47gJCFpKgZc3Dg==,type:str]
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
sops:
    age:
        - recipient: age10u5tg7sqes7uqs4f9s0k449vn4j3kl4x9ge3mulaq2w8crqchu7q5fe6e5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeFZxU2hwaWZNLzF1VG0z
            TXR1bUtvWkt3dTlHSkI0MkxFUEprK09FY0FBCjZRWHl6TWZnaDBVV1dOdW5GV1k2
            SVN3OTR5K01kL2NBbEhVTGovbEk1MkUKLS0tIFlCYXdibGlhZ1NKS2J6aVNPZU9l
            b2xielBvZ1J1ekJkUlYra3Yxdmg5Q3cKMomx+9SKVqjFQ+63YoQrcxlheJ6h0/ud
            9B0wnbLEDSRggBfhYgk8zipXFEIXik3vzoEdUJThW5TAIrD4vlD2LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T22:05:47Z"
    mac: ENC[AES256_GCM,data:aNOOuyAnL4F8xU3KN2QLszqJjoPHcCALJ7p4zmgDZw1vbTY3IDzAYuEpfILheLsSRvlWOnLCgJltW7WHQzCuFfIqLqlCtlunwnoc6BmcK0SUhpCjJXCA6oazn0+8XcI+wc+QbIyS9bBcH8GjT38eJBfX8A4Pwa6iIBpNsWBzr1s=,iv:kDYqH2V7OQmAaueCDi9MnnmsZoYeC+9mqBaWo70gSfU=,tag:EomeAMvn4gp2OdCF4n32Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
