apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik/
  - ./cert-manager/
  - ./cilium/
  - ./cloudflared/
  - ./cloudnative-pg/
  - ../base/cnpg-barman-plugin/
  - ./dragonfly/
  - ./gateway-api/
  - ./hermes/
  - ./infisical/
  - ./kubevirt/
  - ./metrics-server/
  - ./netbird/
  - ./nvidia-device-plugin/
  - ./renovate/
  - ./rook-ceph/
  - ./rustfs/
  - ./secrets-store-csi/
  - ../base/signal-cli/
