---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: staging-lan-gateway-tls
  namespace: staging-cluster-proxy
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: staging-lan-gateway
      sectionName: https
  validation:
    wellKnownCACertificates: "System"
    hostname: "gateway.raymondcollazo.com"
