---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-smartrenergy-pvc
  namespace: wordpress-smartrenergy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
